snakemake/snakemake

- snakemake/io.py
`os.access()` in MacOS has incorrect behavior with `follow_symlinks=False`, so replaces yet another symbolic link judgement.
`os.path.islink()` returns True if the file is symbolic link.
https://docs.python.org/3/library/os.path.html#os.path.islink
`islink()` returns False in the environment which does not support symbolic link (does not raise Exception)
And actually, it can treat files, not only directories.
In detail, please refer the issue #10
> Replace symbolic link judgement in _IOFile.protected

- snakemake/__init__.py
- tests/test_profile/config.yaml
> Allow to define cores as 'all'.

- snakemake/workflow.py
"dict()" is not appropriate value for "default_resources" because workflow.py l.933 assumes "default_resources" has "parsed" attribute which "dict()" does not have.
https://github.com/snakemake/snakemake/blob/44206be0bb278dca61a103e3b1fc873af976a554/snakemake/workflow.py#L933
As default value, "None" would be good because workflow.py l.142 checks the value, and use DefaultResources() if the value is "None".
https://github.com/snakemake/snakemake/blob/44206be0bb278dca61a103e3b1fc873af976a554/snakemake/workflow.py#L142-L146
Current code produces following error when bash completion running, and this PR fix it.
```
File "/Users/smatsumoto/tmp/snakemake-test/venv/bin/snakemake-bash-completion", line 11, in <module>
load_entry_point('snakemake', 'console_scripts', …
```
> Fix "default_resources" initial parameter in "Workflow.__init__"

- snakemake/remote/S3.py
Fix wrong abstract method name "default_" to "default_protocol"
This typo causes following error when use S3.remote with `stay_on_remote=True`, and this PR fixes it.
```
TypeError in line 6 of /Users/smatsumoto/tmp/snakemake-test/lambda1/Snakefile:
unsupported operand type(s) for +: 'method' and 'str'
File "/Users/smatsumoto/tmp/snakemake-test/lambda1/Snakefile", line 5, in <module>
File "/Users/smatsumoto/tmp/snakemake/snakemake/remote/__init__.py", line 91, in remote
```
used Snakefile
```
from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider
S3 = S3RemoteProvider()
rule all_lambda:
input: S3.remote("net-seigot-smtest1/input/hoge.jpg", stay_on_remote=True)
output: S3.remote("net-seigot-smtest1/output/hoge.jpg", stay_on_remote=True)
shell: './lambda_invoker.sh …
```
> Fix wrong abstract method name in remote.S3 ("default_" -> "default_protocol")

- snakemake/io.py
- snakemake/remote/FTP.py
- snakemake/remote/HTTP.py
- snakemake/rules.py
- snakemake/script.py
- snakemake/utils.py
This fixes these warnings: 
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working 
```
Import abstract base classes from collections.abc
> Fix deprecation warnings

- .coveragerc
- snakemake/__init__.py
- snakemake/dag.py
- snakemake/executors.py
- snakemake/jobs.py
- snakemake/workflow.py
- tests/test_ancient/Snakefile
- tests/test_batch/Snakefile
- tests/test_batch_final/Snakefile
- tests/tests.py
This will allow to run workflows in batches.
```
snakemake --batch myrule=1/4
```
ensures that Snakemake will only consider the given partition of the DAG, resulting in much faster evaluation and more convenient execution of very large workflows.
> Initial implementation of batch execution.

- docs/snakefiles/reporting.rst
As described at: http://docutils.sourceforge.net/FAQ.html#is-nested-inline-markup-possible
links cannot be nested within other formatting.
> Remove bold formatting from link

- LICENSE.md
- snakemake/__init__.py
- snakemake/common.py
- snakemake/cwl.py
- snakemake/dag.py
- snakemake/exceptions.py
- snakemake/executors.py
- snakemake/gui.py
- snakemake/io.py
- snakemake/jobs.py
- snakemake/logging.py
- snakemake/output_index.py
- snakemake/parser.py
- snakemake/persistence.py
- snakemake/remote/EGA.py
- snakemake/remote/GS.py
- snakemake/remote/gfal.py
- snakemake/remote/gridftp.py
- snakemake/report/__init__.py
- snakemake/rules.py
- snakemake/scheduler.py
- snakemake/script.py
- snakemake/shell.py
- snakemake/stats.py
- snakemake/utils.py
- snakemake/workflow.py
- snakemake/wrapper.py
- tests/tests.py
This will close #61 by updating copyright headers under snakemake and a tests/tests.py to be from their starting date through 2019. I was tempted to do until 2020 to save some work, but it's probably not right to set it to a future date :)
Note that I did not touch copyright headers for other contributors, as the date reflects the last contribution (or if a range) the first and last.
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
> Updating copyrights to be until 2019 for Johannes

- docs/snakefiles/rules.rst
Corrected typo from 'safed' to 'saved' in section *Defining groups for
execution* in the rules documentation.
> Corrected typo in rules.rst documentation

- snakemake/report/__init__.py
- snakemake/utils.py
Whilst working on the [Reproducible Builds effort](https://reproducible-builds.org/) I noticed that snakemake could not be built reproducibly.
This is due to the default keyword arguments embedding an absolute build path which gets placed literally into any generated documentation:
This was originally filed in Debian as [#932116](https://bugs.debian.org/932116) and [#943956](https://bugs.debian.org/943956)
> Make the documentation build reproducibly

- snakemake/report/__init__.py
- snakemake/utils.py
There was an extra e in `stylesheet` in two locations (read `stylesheeet`) which caused the following error:
```
Traceback (most recent call last):
File "/home/tereiter/github/dom/.snakemake/scripts/tmpjlh6fs25.assembly_report.py", line 181, i
n <module>
combined_stats=snakemake.output.combined_contig_stats
File "/home/tereiter/github/dom/.snakemake/scripts/tmpjlh6fs25.assembly_report.py", line 167, $
n main
report(report_str, report_out, Table_1=combined_stats, stylesheet=os.path.join(atlas_dir,'re$
ort', "report.css"))
File "/home/tereiter/github/killi/databases/conda_envs/df922afa/lib/python3.6/site-packages/sn$
kemake/utils.py", line 265, in report
**files
File "/home/tereiter/github/killi/databases/conda_envs/df922afa/lib/python3.6/site-packages/sn$
kemake/report/__init__.py", line …
```
> Remove typo in stylesheet

- docs/snakefiles/deployment.rst
One of colleagues had trouble finding the `--create-envs-only` flag, so I've added an example to the Distribution and Reproducibility page.
Feedback welcome!
> Add --create-envs-only example to deployment.rst

- snakemake/io.py
Minimal fix for #147 
Something more sophisticated might be to specifically allow `://`, but this does not solve the problem with XRootD
> disable double-/ warning for remote files

- docs/executing/cli.rst
- snakemake/__init__.py
- snakemake/workflow.py
Allow overwriting threads definitions at the command line with `--set-threads RULE=THREADS ...`.
> Overwrite threads

- docs/snakefiles/rules.rst
Fix small typo (redundant word) in rules.rst.
> Typo in rules.rst ("would could")

- snakemake/io.py
Hi,
Importing yaml usually should be a non-issue with snakemake installations. However, when tinkering with the parser, I stumbled accross
``try:
import yaml
except ImportError:
raise WorkflowError("{} file is not valid JSON and PyYAML "
"has not been installed. Please install "
"PyYAML to use YAML config files.".format(
filetype))
``
which does not fit the encountered error.
> io.py: ImportError for yaml module raises same error as a parsing error

- docs/snakefiles/remote_files.rst
- tests/test_remote_azure/.gitignore
- tests/test_remote_azure/README.md
- tests/test_remote_azure/Snakefile
This is a safer and more flexible alternative to using an account key (which is still supported). See official [SAS documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview) and [Sebastian's original PR](https://bitbucket.org/snakemake/snakemake/pull-requests/378/azure-integration/diff). Also refer to email exchange with Sebastian from Thu, Oct 10, 2019.
Happy to provide temporary read/write authentication tokens for testing (the one in the email won't work anymore) and refer to tests/test_remote_azure/README.md
> Added support for Azure storage authentication via SAS

- snakemake/executors.py
Was wondering why my `mem_mb`values were being ignored. The keys need to be checked.
> Fix Tibanna ignoring mem_mb

- .github/workflows/main.yml
- snakemake/executors.py
Snakemake is not removing k8s pods that "Succeeded" until the end of Snakemake's run. This leads to an accumulation of Completed pods that waste resources during long runs. My update deletes pods as they succeed. Pods that have errors are not deleted so the user can investigate their logs. I also altered the CI so it doesn't fail when AWS secrets are missing.
> Delete successful k8s pods.

- docs/getting_started/installation.rst
Just reversing the order, as Bioconda docs state `conda-forge` should take precedence over `bioconda`
https://bioconda.github.io/user/install.html#set-up-channels
> set up conda channel order as bioconda docs recommend

- docs/executing/caching.rst
- docs/snakefiles/rules.rst
Update some rogue uses of 'allows' and a few other minor issues in the `rules.rst` docs.
Happy to change 'us' to 'you', if requested; this would be a bit more in line with the rest of the doc (but 'you' is less friendly than 'us'!)
> Minor grammatical update to rules.rst in documentation

- docs/snakefiles/remote_files.rst
- snakemake/remote/SFTP.py
An option to the remote sftp is added to create the path in the remote
server. This is to be consistent with the standard posix file behavior
of SnakeMake which creates automatically output directories.
The added option is RemoteProvider(mkdir_remote=True)
> added an option to the sftp remote to create output path

- docs/snakefiles/reporting.rst
with the previous example of `pattern=""`, snakemake complains about `pattern` being an unexpected keyword argument for `result()`
> fix `patterns=` example to working keyword, corresponding to keyword in text below

- snakemake/executors.py
Hello Snakemake team,
First thank you for developing and maintaining this great tool. Below the details and solution about a bug I found yesterday.
**Context**: Job submission to SGE cluster using `qsub` from a folder with a path containing special character or white space.
**Problem**: First batch of jobs is successfully submitted but snakemake then hangs forever. This is due to an error generated by the `executors.py` script which prevent job status to be checked. The error is:
```bash
touch: cannot touch `\'XXX/tmp/t&st/.snakemake/tmp.gekxw62y/0.jobfinished\'': No such file or directory
touch: cannot touch `\'XXX/tmp/t&st/.snakemake/tmp.gekxw62y/0.jobfailed\'': No such file or directory
```
The `executors.py` generates a bash script for submission which generates (`touch`) status file …
> executors.py - Quoting correction

- docs/Makefile
- docs/executing/cluster-cloud.rst
- docs/executing/interoperability.rst
- docs/index.rst
- docs/project_info/citations.rst
- docs/project_info/faq.rst
- docs/project_info/more_resources.rst
- docs/snakefiles/configuration.rst
- docs/snakefiles/deployment.rst
- docs/snakefiles/modularization.rst
- docs/snakefiles/remote_files.rst
- docs/snakefiles/reporting.rst
- docs/snakefiles/rules.rst
- docs/tutorial/additional_features.rst
- docs/tutorial/advanced.rst
- docs/tutorial/basics.rst
- docs/tutorial/setup.rst
- docs/tutorial/short.rst
- docs/tutorial/tutorial.rst
- snakemake/gui.html
- snakemake/io.py
- snakemake/remote/NCBI.py
- snakemake/utils.py
- versioneer.py
and fix at least one broken link found while checking.
bio-bwa.sourceforge.net, melpa.milkbox.net and redsymbol.net were excluded because they do not work in HTTPS.
The following links were found to be broken (in both http and https) and currently lack replacements:
http://toolkit.globus.org/toolkit/docs/latest-stable/gridftp/user/#globus-url-copy
http://watson.nci.nih.gov/~sdavis/blog/flexible_bioinformatics_pipelines_with_snakemake/
> Use HTTPS for links where available

- docs/executing/cluster-cloud.rst
- snakemake/__init__.py
In issue #316 I reported that the --dag (and other dot representations) option may not work properly because of other print statements in your Snakefile.
The way these three options work is that a DOT representation of a DAG is printed to the standard output. The documentation recommends you pipe that into `dot` to get a visualization of the graph.
Because Snakefiles are python scripts, it is used by many as such, and people might put `print` statements within the Snakefile. These statements, if redirected to the standard output, may interefere with `dot`.
In this PR, I changed the documentation about visualization and the argparse descriptions of these options to caution people about the use of `print` statements within the Snakefile when trying to get dot representations.
> print statements and --dag, rulegraph and filegraph

- docs/snakefiles/rules.rst
- snakemake/__init__.py
- snakemake/executors.py
- snakemake/rules.py
- snakemake/workflow.py
- tests/test_string_resources/Snakefile
- tests/test_string_resources/expected-results/test.txt
- tests/test_string_resources/expected-results/test2.txt
- tests/test_string_resources/qsub.py
- tests/tests.py
This PR introduces string resources, e.g.
```
rule do_something:
output:
"test.txt"
resources:
gpu_model="nvidia-tesla-p100"
shell:
"some-cuda-tool {output}"
```
> Allow resources to be strings

- snakemake/jobs.py
We are running a large DAG with a lot of groups on SLURM, and I noticed with some additional output that the scheduler only subtracts the core/thread count from the `_cores` resource. Thus if we attempt to throttle our submissions of 100 parallel, "ready" groups to the queue with e.g. `--jobs 20`, Snakemake will submit all 100 groups, even though there is a global `_nodes = 20` resource maximum.
This is our hotfix that assigns a resource of 1 node to each group. In non-cluster mode, I don't think this should have an effect, as I see that the global `_nodes` resource is set to max int.
> Assign nodes resources to groups.

- Dockerfile
- examples/c/README.txt
(I attempted to report this privately, to no response.  Maybe a spam filter blocked it??)
snakemake's Dockerfile uses `wget -O- http://neuro.debian.net/...` to obtain the Neurodebian repository key and address, then uses them to install the singularity-container package.  As http:// is insecure against malicious modification, this is a remote code execution (inside the container) security hole.
The first commit fixes this by using https instead; the second changes an (unrelated and not such a problem, but might as well while we're thinking about it) link to https.
Not addressed here but maybe something to think about: you seem to be using Neurodebian xenial on top of base stretch, which is both mismatched (Ubuntu vs Debian) and old (2016-7).
> Fix security hole in Dockerfile

- snakemake/workflow.py
When working with Kubernetes, files returned by "git ls-files" will be deemed as source files and then uploaded to Kubernetes pods as secrets.
However, if the working directory is a git repository with submodules(https://git-scm.com/book/en/v2/Git-Tools-Submodules), the submodule directory will be returned by "git ls-files" as well, but it's a directory rather than a regular file, so previously snakemake may fail. It has something to do with the this line of code: https://github.com/snakemake/snakemake/blob/v5.15.0/snakemake/workflow.py#L274
The bug can be fixed simply by adding `--recurse-submodules` to the git command (https://git-scm.com/docs/git-ls-files#Documentation/git-ls-files.txt---recurse-submodules).
--------
Version: snakemake v5.15.0
Scenario: call snakemake from a git …
> 🐛 Fix bug to work with git submodules

- snakemake/executors.py
When you create a Kubernetes job, the source files will be uploaded as Kubernetes secrets. However, they have a size limit of 1MB. See: https://github.com/kubernetes/kubernetes/issues/19781
The `KubernetesExecutor.run()` method has already taken this into account by checking secret file sizes. Yet before invoking `run()`, at initialization the method `register_secret()` will be called, which should also check the file size, otherwise an `OSError: (32, 'EPIPE')` may be thrown.
We can solve the problem by checking source file sizes in `register_secret()`, skipping large ones, with warning messages.
----
Version: snakemake v5.15.0
Scenario: call snakemake from a git directory which contains files larger than 1MB, with `--kubernetes` arguments. For example:
```
snakemake --kubernetes …
```
> 🐛 Fix bug to run Kubernetes jobs with large files

- docs/executing/cluster-cloud.rst
Thanks goes to @johanneskoester and @vsoch for the hard work incorporating Google Life Sciences cloud execution. This PR simplifies the language around GPU requests and cleans up some links, code block formatting, and variable highlighting in the docs.
> Fix Google Cloud Life Sciences docs formatting

- README.md
This PR updates the Docker build README status badge to the "Publish to Docker Hub" GitHub Action. The badge link still points to Docker Hub itself.
> Replace Docker build badge with GitHub Actions

- docs/executing/cluster-cloud.rst
This will update the Google Life Sciences executor brief mention under cluster-cloud to:
- include an example command
- remove extraneous description of dependencies 
- include a link to the tutorial!
> Updating google life sciences tutorial to have example command

- docs/snakefiles/deployment.rst
This will produce:
```
Unexpected keyword containers in rule definition ... 
```
> containers keyword

- snakemake/io.py
- tests/test_multiext/Snakefile
Generalization of the `multiext()` command. Allow extensions to start with different characters, not only with `.` .
Example (to catch multiple output files from `macs2 callpeak`):
`output:
multiext("peaks/{sample}", "_peaks.xls", "_narrowPeaks.peak", "_model.R")`
> generalization of multiext output

- snakemake/workflow.py
- tests/test_multiple_includes/Snakefile
- tests/test_multiple_includes/test_third_rule.smk
This addresses #220 .
I have implemented the "easiest" solution to the problem. I tried following the issue upstream, but allowing `snakefile` to be "PathLike" would not be a simple fix I think. However, if you think there is a nicer way of implementing the ability to use `pathlib.Path` objects in `include` directives point me at the relevant code and I can make the changes.
On a side note, I noticed quite a lot of unused `import` statements. Would you like me to clean those up? (Will take one second - thank god for JetBrains/PyCharm)
> Allow include directive to take a pathlib.Path object

- snakemake/dag.py
- snakemake/jobs.py
ensure job uniqueness via a factory, and use the fast default object hash and eq for job objects.
> Speed up job hash and equality checks

- snakemake/workflow.py
There is no reason to build a DAG if the `--unlock` argument is given.
> unlock before building DAG

- snakemake/__init__.py
If cluster mode is enabled then cores is set to `None` on line 363, which results in a `TypeError` in the following comparison statement.
> Rearrange conditional statement in debug check

- snakemake/dag.py
- snakemake/deployment/conda.py
- snakemake/exceptions.py
- snakemake/logging.py
- tests/tests.py
This PR enables to consider alternative paths in the DAG if an input function fails. To make this change more accesible, the --debug-dag output has been extended to include all ignored exceptions that occur during DAG evaluation.
> Smart input function exception handling

- docs/snakefiles/deployment.rst
In the [webversion](https://snakemake.readthedocs.io/en/v5.20.1/snakefiles/deployment.html#using-environment-modules) the \`something\` was shown as italic, missing one dash  before use-envmodules. (-use-envmodules instead of --use-envmodules)
> highlight as code

- snakemake/executors/__init__.py
The hardcoded `--latency-wait 0` was causing some jobs to fail for me. Passing `{latency_wait}` instead mimics other `executor` classes e.g. `ClusterExecutor`:
https://github.com/snakemake/snakemake/blob/f62792d69c28e937243ca8b4f7cac3cec868adcc/snakemake/executors/__init__.py#L622
> Pass latency_wait to kubernetes jobs

- snakemake/remote/GS.py
Currently, we use the google storage bucket as an index for the cache, even though weve only potentially checked one subfolder. This leads to an error that we think weve indexed the bucket but we have not, and an MissingInputException suite of errors. This will resolve #511 and #546.
> fixing gs cache prefix

- snakemake/executors/__init__.py
- tests/test_tes/Snakefile
- tests/test_tes_ftp.py
- tests/test_tes_ftp/Snakefile
- tests/test_tes_ftp/envs/gzip.yaml
- tests/test_tes_ftp/scripts/test_script.py
FTP support successfully tested with Funnel TES for FTP input but not output files (553 error when trying to upload files).
Code changes are not finalized (some leftover/debug code around).
Apart from FTP support, these issues were addressed via different commits (could be easily cherry-picked for a separate PR if desired):
* improve logging (more log messages, more consistent)
* enforce rate at which TES status is polled (did not seem to have worked previously)
* allow passing input/output files by content (good for Snakemake file and related input files that are not really part of the task)
* get task description from rule message, if present
> feat(tes): towards supporting FTP files

- docs/executing/cloud.rst
- setup.py
- snakemake/remote/GS.py
The quotes for any --default-resources command line arguments need to be around the whole group.
> Fixing quotes for --default-resources example

- snakemake/executors/google_lifesciences.py
I'm not sure why this issue popped up (#555) because it didn't happen with the full testing run last night, but these two changes (to logging and init of the discovery client) seem to be the recommended fix. Another option would be to return to the pinned Google library versions. I guess it's up to how we want to move forward - if we pin versions, we are less likely to see errors like these, but then perhaps we _do_ want to see them so we can stay up to date with the Google client updates.
> adding instruction to skip cache for google discovery client

- CHANGELOG.rst
- snakemake/__init__.py
I find myself using `--restart-times` a lot. And I'm lazy. So I added a short option. Happy to change it to another letter if `-T` is not to your liking?
> add short option for restart times

- snakemake/remote/GS.py
This should be a quick fix to convert the GS blob timestamp (when last updated) to an int (since epoch time) so we can compare. This will fix https://github.com/snakemake/snakemake/issues/572. Here is how I quickly tested:
```
blob.updated
datetime.datetime(2020, 6, 2, 10, 56, 4, 988000, tzinfo=<UTC>)
blob.updated.timestamp()
1591095364.988
int(blob.updated.timestamp())
1591095364
```
> converting GS updated datetime to epoch time float timestamp

- docs/project_info/faq.rst
the linked solution does not really work as advertised. This adds a working option directly to the FAQ.
> add working example for updating git files

- docs/snakefiles/rules.rst
This PR documents the new default behaviour introduced by PR #249 .
Hopefully, this helps addressing questions such as the one raised in issue #521 .
> describe new default behaviour regarding environment variables for linear algebra and OpenMP

- docs/snakefiles/deployment.rst
Corrected the flag name for creating conda-environments on air-gapped systems.
According to `snakemake -h` the flag must be `--conda-create-envs-only`
> Wrong flag in documentation

- snakemake/scheduler.py
This removes the space from the LpProblem name to prevent the following warning:
`warnings.warn("Spaces are not permitted in the name. Converted to '_'")` from https://github.com/coin-or/pulp/blob/76b28fb9005ca2e78974c80dd8dd2ef2d696f1f6/pulp/pulp.py#L1194-L1195.
> remove space from problem name

- snakemake/utils.py
Detect the case where a user has put a wildcard in the shell commands
without prefixing with "wildcards." This allows giving a useful error
message, rather than the more generic NameError message.
> Detect and give useful error for missing "wildcards."

- snakemake/executors/google_lifesciences.py
- snakemake/executors/google_lifesciences_helper.py
This will address discussion in #457 to save google life sciences logs from the instance to cloud storage. This works by way of:
- modifying the same download script to also handle uploads, the one in the gist. Note that I'm also adding the source code here (google_lifesciences_helper.py) so that after it's merged, we can update to use this file instead of a random gist.
- defining a google life sciences logs directory to be in the storage prefix + google-lifesciences-logs + `<job name>`
- adding an extra action after the job step to save whatever output is found under `/google/logs` to this location
- giving the user a message to look for them here.
Along with debub statements for the logging directory, the message to the user is also updated to include where to look for logs:
```
Get …
```
> adding google life sciences logging save to storage bucket

- Dockerfile
The Dockerfile prior to this commit install Singularity version 2.x. This commit installs Singularity 3.x from source. This commit also adds multi-stage builds, so unnecessary programs are not present in the final image. The separate stages can be built in parallel with `DOCKER_BUILDKIT=1 docker build .` on systems that have BuildKit.
This commit is a result of the comment https://github.com/snakemake/snakemake/pull/371#issuecomment-625167668. Podman can replace the Singularity installation in the future.
> ENH: use multi-stage builds + install singularity from source + use nonroot user

- snakemake/__init__.py
This is completely minimal and could be done in other ways, but I just want to see what you think. I haven't run any tests as I'm not sure how one does that.
I suggest adding this because I just did this:
```sh
$ snakemake --config xxx=33 target
```
and got the "Invalid config definition: Config entries have to be defined as name=value pairs." error message. Turned out that because `--config` can accept many key/value pairs, Python's argparse (I guess) was adding `target` to the list of values assigned to `config`. But the error message didn't show me what was going wrong until I went in and changed the code to print the troublesome value.
This doesn't happen if the user uses `snakemake --config xxx=33 -- target` but not everyone will be in the habit of doing (or even know about) this. …
> Added info about unparseable argument to parse_key_value_arg

- Dockerfile
Reverts snakemake/snakemake#531. It seems like the changes cause issues with cloud execution: https://github.com/snakemake/snakemake/runs/1090789849#step:11:591
> Revert "ENH: use multi-stage builds + install singularity from source + use nonroot user"

- setup.py
Testing update of pulp to avoid Python 3.8 deprecation of time.clock (used in solvers.py). This will close #617 (if it works!).
> Updating pulp >=2.0

- snakemake/scheduler.py
It happens that ilp scheduling fails caused by a too long LpVariable-name(see [https://github.com/snakemake/snakemake/issues/635](https://github.com/snakemake/snakemake/issues/635)).
This occurs as the scheduler takes the name of a temp file as variable name.
Additionally, based on the file name pulp throws warning incase it contains illegal characters.
To solve both issues variables variables now consist of a prefix (preventing the illegal character warning) and a index value replacing the file names. Ensuring that variable names keep short and do not contain any special characters.
> Fix lpvariable

- docs/tutorial/setup.rst
Miniconda download locations [have moved](https://docs.conda.io/en/latest/miniconda.html#miniconda). Fixes #612.
> Update Miniconda download URLs

- snakemake/executors/google_lifesciences.py
We want to update the GLS executor to use the helper script provided in the repository, instead of the one in a gist. The gist is here https://gist.githubusercontent.com/vsoch/f5a6a6d1894be1e67aa4156c5b40c8e9/raw/a4e9ddbeba20996ca62745fcd4d9ecd7bfa3b311/gls.py in case anyone wants to do a comparison!
> Updating google_lifesciences.py

- snakemake/__init__.py
- snakemake/executors/__init__.py
- snakemake/jobs.py
- snakemake/persistence.py
- snakemake/scheduler.py
- snakemake/workflow.py
Very large numbers of metadata files in the .snakemake/metadata folder can lead to slow performance on network file systems (e.g. Lustre) when checking if jobs are incomplete (--rerun-incomplete). 
1) This code separates the metadata and job-incomplete tracking, by creating an extra .snakemake/incomplete folder.
For the latter, it implements caching, as a simple file existence check suffices to determine if a job is incomplete.  The number of tracking files in the incomplete folder usually remains low, as these are deleted after a job finishes. This results in large speedups when combining --rerun-incomplete with a workflow with many files on a network file system.
Code has been added to enable backwards compatibility with the current .snakemake folder structure.
2) The PR adds also a …
> Separate metadata and incomplete job tracking

- snakemake/dag.py
- snakemake/io.py
- snakemake/scheduler.py
Large workflows (njobs>10k) can become very slow due to some code which scales O(n^2). 
* Change candidates in update_needrun from list to set 
(enable quick member check)
* Use deque for faster bfs jobs traversal
(prevents memory copy due to popping of first item)
* Optimize open_jobs using set operations.
* Only run open_jobs if new jobs have potentially been added to ready jobs
* Add short-circuits to the periodicity detector to improve its speed.
> Optimizations to handle large workflows

- snakemake/workflow.py
- tests/test_google_lifesciences.py
- tests/test_touch_remote_prefix/Snakefile.touch
- tests/test_touch_remote_prefix/expected-results/fileJob1
This should address an issue that using touch() in a Snakefile with a remote prefix seems to strip away the touch (and likely any other flags that were present with the output or input argument. The reason comes down to the apply_remote_prefix function for a rule, which uses the workflow.apply_remote_prefix. In the case that an AnnotatedString is passed (with one or more flags such as touch) the conversion to a fullpath to derive the remote path strips away the annotations. This PR does a simple fix to check if the path has a flags attribute, and if so, update the object to maintain them. We assume that:
- There will be no other passed types that have an equivalent flags attribute that might be mistakenly added
- The original path cannot have a remote_object flag already defined (that …
> fixing bug with using touch alongside remote prefix

- snakemake/executors/google_lifesciences.py
The `exec_job` should apply the parameterized value, or default, of `latency_wait` that was provided to the GoogleLifeSciencesExecutor. 
The value was fixed at 0 with `--latency-wait 0`. Changing this to `--latency-wait {latency_wait}` means it will accept the user's configured `latency_wait` value or the default value of `3`.
> apply latency-wait argument value to GLS job

- snakemake/io.py
- snakemake/remote/GS.py
- snakemake/remote/__init__.py
File stat operations are slow on network filesystems such as Lustre. When stat operations are not cached,
preparing the DAG becomes very slow for large workflows, with multi-hour runs at <10% cpu usage.
This PR starts from the recently added IOCache inventory framework, and makes the following changes:
* Enable local inventory caching for absolute paths:
(currently nonfunctional as root = path.split("/", maxsplit=1)[0] in get_inventory_root will 
be an empty string, and therefore need_inventory will be False for these paths)
* Perform only an inventory of the directory of the file, and not of its subdirectories.
This leads to more predictable behaviour, as an inventory is only obtained of directories
with workflow files. 
* get_inventory_root/path is moved from IOCache to IO/Remote …
> Threaded local iocache

- docs/getting_started/installation.rst
Following the docs after a co-worker mentioned Snakemake in an internal chat :+1: and found that the Mamba repository had changed, and GitHub is taking care to redirect users, but probably safer to just use the new URL.
Thanks for the great docs BTW!
Bruno
> [docs] Update mamba github link

- docs/executor_tutorial/azure_aks.rst
- docs/executor_tutorial/google_lifesciences.rst
Hi,
reStructuredText and sphinx are not my forte, but I think the Python link is broken as it's missing the link reference in the `.rst` file?
Cheers
Bruno
> [docs] Fixing reference and link to Python

- docs/tutorial/basics.rst
Hi,
Was almost finishing my goal for reading Snakemake docs for tonight, when I spotted one issue in the rendered tutorial.
Haven't tested this syntax yet (sorry, :bed:  time :zzz: ). I copied from another file, removing the extra `_`. Will try to render it locally after I set up my environment build docs if I have time during breakfast or $work break :+1: 
Cheers
Bruno
> [docs] Fix link in tutorial for snakefiles rule ref

- misc/nano/README.md
- misc/nano/syntax/snakemake.nanorc
- misc/vim/syntax/snakemake.vim
Add a nano syntax highlighting file for Snakemake (snakemake.nanorc), extended from the python.nanorc file.
> Add a nano syntax highlighting file

- snakemake/dag.py
- snakemake/exceptions.py
Currently, a missing output file leads to an exception indicating the file, but not the job id. Tracing issues is much easier if at least the internal job ID is available to find matching log files (which may not contain the respective file name).
> Show Job ID on missing output error

- tests/test_google_lifesciences.py
- tests/test_kubernetes.py
This will update the GLS tests to dynamically create and destroy buckets, which we need to do now since the base snakemake-testing won't reliably exist.
> updating google life sciences tests

- docs/conf.py
- docs/project_info/faq.rst
- misc/vim/ftdetect/snakemake.vim
* FAQ: add section about possibility of formatting Snakemake files with `snakefmt`
* Add Sphinx extension to `conf.py` allowing easy internal header referencing as per [here](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-sections-in-the-same-document)
* FAQ: rewrite syntax highlighting section, referencing the vim README page. Also in this FAQ section, reference `snakefmt`'s new vim plugin for formatting
* Vim filetype detection: placed in one line and use two canonical Snakemake filename patterns only : 'Snakefile' and '*.smk'
For the last bullet point: the FAQ currently reads that Snakemake files are `Snakefile` and `*,smk` (https://snakemake.readthedocs.io/en/stable/project_info/faq.html#id20) but the filetype detection plugin detects `Snakefile`, …
> Add snakefmt mention in faq and streamline vim

- snakemake/report/__init__.py
This PR fixes an issue where snakemake prints the path of the last auxiliary file handled in line [935](https://github.com/snakemake/snakemake/blob/af879e08f3fc56766202337de70700abbe3a6f9f/snakemake/report/__init__.py#L935) returning something like `Report created: some/aux/file.extension`
This happens as the variable `path` gets overwriten during handling auxiliary files [916](https://github.com/snakemake/snakemake/blob/af879e08f3fc56766202337de70700abbe3a6f9f/snakemake/report/__init__.py#L916).
To prevent this the variable has been renamed .
> Fix logging path for snakemake report

- snakemake/jobs.py
Previously the `--list-code-changes` option did not work for included rules  with the `script` or `notebook` directive if the rule was included in a subdirectory
The reason was that the code looked for the included file relative to the top directory rather than the rules subdirectory.
This commit fixes this, thereby addressing #417
> fix `--list-code-changes` for included rules

- misc/vim/ftplugin/snakemake/folding.vim
- misc/vim/ftplugin/snakemake/sections.vim
Added section navigation and folding to snakefiles.
Section navigation moves between top level rules, checkpoints and functions.
Folding is more opinionated and assumes most python work occurs in the preamble (before the first rule) while the rest of the file contains input functions and rules.  Python code interspersed after the preamble will be folded with the previous rule in most cases unless there is an indented rule, e.g. anonymous rules in a for loop.  The commit message has an annotated example.
> Vim fold sections

- snakemake/io.py
The `asyncio.create_task` method was introduced with python 3.7. To be
compatible with older version, we should use
`asyncio.get_event_loop().create_task`
https://github.com/snakemake/snakemake/issues/725
> Fix asyncio create_task syntax for compatibility with python < 3.7

- snakemake/workflow.py
Passes cores to subworkflows at evaluation time. Resolves #208.
> enable (local) multithreaded subworkflows

- snakemake/__init__.py
While there has been a lot of discussion on `--cores` as a required option and what, if any, a default should be (e.g. #283, #308, #312, #450 ), based on stepping through the code, if I am not mistaken it appears `--unlock` can be safely excluded from requiring `--cores` if `local_exec`. I tested this change locally. Closes #530.
The relevant function calls for unlocking:
https://github.com/snakemake/snakemake/blob/a813ea96fcd546c63654f06ce67e429104e5ca5c/snakemake/workflow.py#L683-L687
https://github.com/snakemake/snakemake/blob/a813ea96fcd546c63654f06ce67e429104e5ca5c/snakemake/persistence.py#L175-L176
https://github.com/snakemake/snakemake/blob/a813ea96fcd546c63654f06ce67e429104e5ca5c/snakemake/__init__.py#L767-L768
https://github.com/snakemake/snakemake/blob/a813ea96fcd546c63654f06ce67 …
> Allow --unlock without --cores locally

- .github/workflows/main.yml
- snakemake/scheduler.py
* use GB for temp file size, avoiding too large integers.
* if ILP solution is empty, fall back to greedy scheduler.
> fix a corner case where the ILP scheduler generates an empty solution

- snakemake/report/__init__.py
This PR adds the missing import of the function `contains_wildcard` in `report/__init__.py`, which caused https://github.com/snakemake/snakemake/issues/745
> Added missing import.

- snakemake/__init__.py
With the changes made in https://github.com/snakemake/snakemake/pull/709 booleans (True/False) do not get recognized anymore as booleans, but as their string representation. My guess is that was an unintended side-effect. This should fix that.
example command: `snakemake -j1 --config mybool="True" --dryrun --quiet` and if we would print the config in the Snakefile
5.27.4
{'mybool': True}
5.28.0
{'mybool': 'True'}
this PR
{'mybool': True}
> parse_config recognizes bools

- snakemake/workflow.py
In my hands this fixes the behavior observed in issue #783, allowing subworkflows jobs to also be executed in parallel .
This was achieved by passing the 'nodes' argument to subworkflows.
This fix is essentially a copy of: https://github.com/snakemake/snakemake/pull/723
Is there anything else that would similarly profit from being passed to `subworkflows`?
> Fix Issue #783: Pass `nodes` to subworkflows to allow parallel execution on cluster backend.

- snakemake/persistence.py
The starttime metadata for run rules would be set to None since the `_incomplete_path` did not seem to exist for them. Instead, fall back to using the `_metadata_path`.
I do not fully understand the changes that caused this bug, and thus, while this seems to fix things to me, I don't know that this is the right way to fix things.  @mhulsman or @johanneskoester You two worked on the PR related to this, perhaps you could help me understand the proper way to fix things?
Resolves: #741
> Fix metadata starttime

- snakemake/rules.py
This includes expanding params, inputs, and log files. This fixes a bug when providing a Path or list of Path as the return value of an input function, for example.
> Allow Paths wherever wildcards are applied

- snakemake/__init__.py
- snakemake/logging.py
This is the first round of work to address #799. Specifically, we have the WMS monitor as a proper logger, and don't need to do any customization in the setup_logger function. We are currently using the defined API schema (defined by panoptes) although the project is thinking about changing this to some spec (see https://github.com/panoptes-organization/monitor-schema/pull/7#issuecomment-750897929). The spec in question doesn't have an update workflow endpoint, so I'm not sure how that would work yet, but I think @fgypas perhaps has something in mind.
In addition, we have added authentication, which is optional and enforced by the WMS monitor server. If authentication is required, the user must export `WMS_MONITOR_TOKEN` in their environment, which is provided by the server. We could do …
> formulating wms monitor into logger proper

- snakemake/dag.py
This is faster and simpler than always updating jobids during a checkpoint handling. The jobid update happens during postprocess at the end of the checkpoint update.
Fixes #817.
> do not access jobid during checkpoint update

- snakemake/__init__.py
- snakemake/executors/__init__.py
- snakemake/workflow.py
Changes the `executesubworkflows` argument in `Workflow.execute` to the `execute_subworkflows` attribute of `Workflow`, enabling `get_additional_args` to add the `--no-subworkflows` command to the cluster submission script when appropriate.
> fix #821: enable --no-subworkflows command when using --cluster

- snakemake/executors/google_lifesciences.py
GLS does not support Singularity, but we currently issue a warning and continue. We should be raising a workflow exception and giving a clear message to the user that Singularity is not supported. See https://github.com/snakemake/snakemake/pulls#issuecomment-751803456.
> ensure that singularity with GLS exits with a clear error message

- CHANGELOG.rst
- snakemake/dag.py
- snakemake/executors/__init__.py
- snakemake/jobs.py
- f-strings in runtime code were replaced with `format` syntax as we still support python 3.5
There are also f-strings in the following files but I didn't touch them as I think they are in files that will only be executed in dev environments.
```
tests/common.py: line 198
docs/snakefiles/rules.rst: lines 1374, 1385, 1387
```
> Remove f-strings

- snakemake/rules.py
This change makes it easier to find and fix the offending rules:
> Wildcard constraints in inputs are ignored. 
is changed to
> Wildcard constraints in inputs are ignored. (rule: my_rule_name)
> Add rule name to warning about wildcard constraints in inputs

- snakemake/report/report.html.jinja2
This PR fixes a bug where the results in the report keep loading endlessly in case no caption is provided for a result (see https://github.com/snakemake/snakemake/issues/862).
> Report: Fix missing caption in results

- snakemake/report/__init__.py
Currently zipped snakemake-reports no not contain any compression as the default compression method is `ZIP_STORED`.
As that method does not perform any compression it appears reasonable to me setting the compression method to `ZIP_DEFLATED` with a default compression level of 6.
In a test run a 4.8GB zipped snakemake-report got reduced to 1.3GB.
> Enable compression for zipped reports

- snakemake/executors/__init__.py
- tests/test_github_issue627/Snakefile
- tests/test_github_issue627/Snakefile.internal
- tests/test_github_issue627/config.yaml
- tests/test_github_issue627/job.py
- tests/test_github_issue627/local_job_status.sh
- tests/test_github_issue627/run_locally.sh
- tests/tests.py
Originally, when running in `--cluster` mode, snakemake relied on the child snakemake-processes within the cluster jobs to delete their output files if they failed. In practice, e.g. when using the SLURM scheduler, the jobs are killed with SIGKILL if they run over their time or memory limits. This made it impossible for them to clean up their own output files. There are workarounds for that, but especially running out of memory seems impossible to handle to me.
That is why the master process of snakemake should handle the cleanup, if running on a cluster. This process can detect if a job has failed or not (with custom `--cluster-status` if necessary), and can then clean up after the child process.
This works at least if the master process is active during the whole computation, but e.g. …
> Ensure output files of failed jobs are always removed in cluster mode

- snakemake/report/report.html.jinja2
It turned out that a previous PR (https://github.com/snakemake/snakemake/pull/863) did not fix the issue of endlessly loading snakemake-report results when no caption is defined.
Since the last change this behavior now occures in case a caption is set, as the jinja-Template creates a term containing multiple quotes (see https://github.com/snakemake/snakemake/issues/862#issuecomment-776893513).
This PR should solve this issue by setting `""` als default value in case no caption is set.
> Fixing caption in report

- docs/executing/cli.rst
- docs/tutorial/advanced.rst
Per https://github.com/snakemake/snakemake/issues/885#issuecomment-785357924, fixes the `--cores` documentation in two places to make it clear that `--cores` is a required argument.
I did not do an extensive search of the docs for other places to update, though, so you might leave this open for a bit.
> update --cores documentation

- snakemake/dag.py
This can happen when updating multiple checkpoints.
> fix KeyError caused by jobid query before new jobids were assigned

- snakemake/__init__.py
This fixes an issue when using `--profile` configs that give a value for `--cluster` that has arguments.
In config.yml, relative paths to e.g. scripts that wrap qsub can be given, and snakemake attempts to inteligently find the full path ot each script. However, the full value of `--cluster` is used, which can contain arguments (e.g. job dependencies).
For example, with a profile `/path/to/profile/config.yml`:
```
cluster: "jobsubmit --depend '{dependencies}'"
```
Currently, snakemake will search for `/path/to/profile/jobsubmit --depend ...`, i.e. with the args intact. The attached patch tests not only `os.path.exists(pathwithargs)`, but also `os.path.exists(shlex.split(pathwithargs)[0])` to get the path to the script itself.
> Fix issue w/ --cluster script with args in profile

- docs/snakefiles/modularization.rst
This is based on [an issue over at snakemake-wrappers](https://github.com/snakemake/snakemake-wrappers/issues/237) and [the solution @nikostr found](https://github.com/snakemake/snakemake-wrappers/issues/237#issuecomment-818658275). So we should also document this here---as concisely as possible---in the hope of avoiding such digging for others.
> docs: add example for wrapper inclusion via GitHub url

- snakemake/unit_tests/__init__.py
This PR fixes a typo in the flag suggested when running snakemake with the `--generate-unit-tests` flag.
> Fixes #972

- docs/snakefiles/remote_files.rst
- input of `all` rule is local files, so don't use `XRootD.remote`
- `file_numbers` is the attr `n` of the return value of `glob_wildcards`
> Documentation: fix XRootD remote file example

- snakemake/common.py
- snakemake/jobs.py
- snakemake/rules.py
Previously a param value that depended on input that had not been generated previously would fail. Analogous to how resource expansion occurs, I might expect the param expansion to identify the value depends on input not yet available, and display a <TBD> value.
These changes allow for that features by moving the code which handles this in resource expansion to the more general `apply_input_function`. With the FileNotFoundError handling occurring there, the code in the resource expansion could be simplified. 
This was tested on and passed the minimal reproducible example, resolving #927, but may interfere in unexpected ways with other code.
The output of `snakemake -n -p` for a rule with `shell: echo {params}` where the param depends on the input now looks something like 
```
echo <TBD> …
```
> Allow params expansion to handle FileNotFoundError (fixes #927)

- setup.py
This fixes issue #991, which is triggered when installing the latest version of snakemake-minimal from Conda.
> Set minimum version of smart_open to 3.0

- snakemake/utils.py
This PR allows to set `filename_params=True` when creating a Paramspace object in order to automatically use all columns.
This is useful when immediately passing the dataframe to Paramspace:
```python
import pandas as pd
from snakemake.utils import Paramspace
paramspace = Paramspace(pd.read_csv('config/params.csv'), filename_params=True)
```
> Paramspace enhancement: Use all dataframe columns when `filename_params == True`

- snakemake/common.py
Otherwise, slashes would be replaced with backslashes.
> do not norm URL source paths on windows

- .github/workflows/main.yml
- snakemake/report/__init__.py
- tests/test_report/Snakefile
- tests/test_report_dir/Snakefile
- tests/test_report_zip/Snakefile
- tests/tests.py
This PR enables testing on windows of the ``--report`` functionality. It works nicely. This was previously skipped for windows since no conda-forge "pygraphviz" package existed for windows. 
The PR also fixes a minor problem with imagemagick convert on Windows by using `magick convert instead of `convert`. The 'convert' command in imagemagick has been deprecated because it conflicted with built in tools on windows. 
Finally it updates Windows tests to run against python 3.9.
> Enable testing report functionality on Windows

- snakemake/io.py
Fixes: #433
"Utf-8" is still not the default encoding on windows. So it must be specified when reading the config file.
> Fixes missing encoding on Windows when reading config file

- snakemake/jobs.py
Put pipe producer and consumer on the same toposort level in group jobs, such that they are considered to be executed simultaneously.
> Group toposort pipe

- snakemake/jobs.py
- snakemake/script.py
- snakemake/sourcecache.py
Fixes issue https://github.com/snakemake/snakemake/issues/1059 and https://github.com/snakemake/snakemake-wrappers/issues/382.
> If necessary, create tmpdir before job is executed. Fix bug in source cache when using git+file URLs. Pass resources to script shell commands.

- docs/executing/cli.rst
Remove whitespace before `` to  allow `someoption:` to be rendered correctly as code.
> fix: remove whitespace before ``

- docs/snakefiles/rules.rst
Slight rewording of `rules.rst`
I'm happy for maintainers to cherry pick/edit what they like and leave the rest.
I don't know why Github claims in the diff that I changed the end of the file. I didn't. Maybe it's a Github bug?
> [Suggestion] Slight language changes to `rules.rst`

- snakemake/remote/FTP.py
- tests/test_github_issue1062/Snakefile
- tests/test_github_issue1062/expected-results/.gitignore
- tests/tests.py
Fixed a typo in the parameter checks for remote.FTP that seems to be causing issue #1062
> Bugfix for Issue #1062: correct a typo in parameter checks

- docs/conf.py
Should fix #1071 
I haven't tested this myself, but I'm fairly confident that the simple switch should not break anything.
The documentation is clear on this: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file
> fix: add_stylesheet() was deprecated in Sphing v1.8 (#1071)

- docs/conf.py
Reject if there's a reason why copyright should stop in 2021, otherwise, probably better like this, even just for the looks.
Possible extension: make the year bump automatic with datetime. Is there a reason not to do this @johanneskoester?
> Bump copyright period to 2021

- docs/conf.py
Fixes #1082 
Also, fixes a syntax error introduced in #1076.
Tested building the docs locally, and am confident it should fix the issues without breaking anything.
> docs: Fix syntax error in docs/conf.py and update sphinx.ext.napoleon import

- snakemake/deployment/conda.py
In 6.4.1 we had refactored the Conda class, which accendentally led to superfluous calls of `conda info`. This is fixed now.
Many thanks to @christopher-schroeder for spotting the issue and narrowing down to the Snakemake version that introduced the fix.
> fix: avoid superfluous calls of conda info that have slowed down Snakemake since 6.4.1.

- snakemake/rules.py
Input functions that throw a FileNotFoundError could have let to a KeyError when handling the exception.
> fix: avoid spurious KeyError when handling FileNotFoundError in input functions.

- snakemake/shell.py
- tests/test_strict_mode/Snakefile
- tests/tests.py
Bash strict mode (`set -euo pipefail`) was disabled on Linux in v6.5.0. This PR adds back bash strict mode and adds a test for bash strict mode.
This PR should fix #1121. Thanks to @ptrebert for identifying the problem.
> fix: Re-enable bash strict mode on Linux

- snakemake/dag.py
Link to the issue: https://github.com/snakemake/snakemake/issues/1106
Bug description on StackOverflow: https://stackoverflow.com/questions/68514884/ambiguousruleexception-when-there-is-no-ambiguity
The AmbiguousRuleException is being thrown whenever there is no ambiguity. This behaviour is not deterministic, and there is no simple way to predict whether the invocation of the pipeline would produce this error.
The actual problem is incorrect algorithm of rule selection out of the list of possible producers. This list is being sorted, but there is no strict order of the rules unless explicitly specified by `ruleorder`. The rule that has no explicit `ruleorder` is neither greater nor smaller than other rules, and the result of sorting such a list becomes incorrect. Consider three rules: …
> fix: AmbiguousRuleException bug caused by weak ordering of rules

- snakemake/executors/__init__.py
> fix: efficient job status checking when using DRMAA API (this should yield much better parallelization and performance when using --drmaa)

- docs/snakefiles/rules.rst
The snakemake documentation is generally excellent, but I figured it can't hurt to fix this small typo I found. Thanks!
> docs: Typo fix if rules.rst

- snakemake/workflow.py
- tests/conftest.py
- tests/test_github_issue1158/Snakefile
- tests/test_github_issue1158/qsub.py
- tests/tests.py
> fix: Disable Persistence cache for snakemake jobs

- snakemake/dag.py
> perf: improve job selection performance in case of potential ambiguity that is resolved by comprehensive ruleorder statements.

- snakemake/common/__init__.py
- tests/testapi.py
Fixes: https://github.com/snakemake/snakemake/issues/1105
> fix: async_run to allow nested event loops.

- snakemake/jobs.py
This is not exactly a fix but removes a `print`-command which seems to be missed during cleaning up.
> fix: Remove unnecessary output

- snakemake/caching/hash.py
- snakemake/report/__init__.py
Creating a snakemake report currently fails due to a missing argument when calling 'get_source' and a mismatching number of returned values.
> fix: fix function call when creating report and hashes for between workflow caching

- .github/workflows/conventional-prs.yml
- snakemake/jobs.py
- snakemake/sourcecache.py
> fix: fixed code change detection when using modules

- snakemake/__init__.py
- snakemake/workflow.py
> fix: handle config file extension/overwriting more explicitly

- snakemake/jobs.py
> feat: fail with an error if snakemake cannot write job metadata.

- snakemake/notebook.py
- snakemake/script.py
Snakemake 6.10 was unable to open Jupyter Notebooks for editing as the use of LocalSourceFile objects for file paths was not supported in notebook.py or script.py (affecting Notebooks). This PR addresses that issue (logged as GH Issue #1253  )
> fix: Issue #1253 (problems editing Jupyter Notebooks)

- docs/snakefiles/rules.rst
- snakemake/__init__.py
- snakemake/executors/__init__.py
- snakemake/jobs.py
- snakemake/notebook.py
- tests/test_jupyter_notebook_draft/Snakefile
- tests/test_jupyter_notebook_draft/data.txt
- tests/test_jupyter_notebook_draft/env.yaml
- tests/test_jupyter_notebook_draft/expected-results/Notebook.py.ipynb
- tests/tests.py
This will allow to use the notebook integration of VSCode instead of firing up an own server.
> feat: add flag --draft-notebook for generating a skeleton notebook for manual editing (e.g. in VSCode).

- snakemake/__init__.py
- tests/tests.py
The snakemake API specifies:
```
cores (int) – the number of provided cores (ignored when using cluster support) (default 1)
nodes (int) – the number of provided cluster nodes (ignored without cluster support) (default 1)
```
However https://github.com/snakemake/snakemake/commit/16c34c8c09f471558950d1c3755de71e38e1043d introduced a "bug" where if you use the api, e.g. `snakemake.snakemake("Snakefile", cores=10)` then cores would be set properly to 10, but `nodes` defaults to 1, so only one job at most works in parallel.
This should be fixed with this tiny change. 
**edit**
Ok somehow this gave an issue in the tests. The test needs 5 threads minimum due to many pipes, and only 3 were specified. That shouldn't have worked to begin with, so I would say this PR "works". However I'm not so …
> fix: snakemake API using only 1 job as default

- docs/snakefiles/rules.rst
Quick fix for a little typo regarding the new `—draft-notebook`-option.
> docs: Fix typo in rules.rst (—draft-notebook)

- docs/snakefiles/deployment.rst
A comma was missing between arguments in several code blocks.
> fix: typos in code examples

- snakemake/sourcecache.py
> fix: fix source cache handling for remote source files retrieved via github() or gitlab() tags.

- snakemake/executors/__init__.py
Fixes #1108.
The --conda-frontend flag is now appended to the Snakemake command used by the ClusterExecutor and the CPUExecutor, just like --conda-prefix. The default of "mamba" no longer interferes if the user wishes to use "conda".
> fix: --conda-frontend value not passed on to cluster jobs

- docs/snakefiles/deployment.rst
- snakemake/deployment/conda.py
- tests/test_deploy_script/Snakefile
- tests/test_deploy_script/test-env.post-deploy.sh
- tests/test_deploy_script/test-env.yaml
- tests/tests.py
> feat: support for post deploy scripts

- docs/snakefiles/modularization.rst
- orthography fixed in "Modules" section
- removed implicit pointers to code `first statement`, `second statement` which could be misleading
* ~~[ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.~~
* ~~[ ] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).~~
> docs: wording fix in Modularization section

- docs/getting_started/installation.rst
Resolves #1328 by linking the bioconda recipe in the installation page of the documentation.
> docs: link to list of dependencies from installation

- docs/project_info/more_resources.rst
I updated the URL to download emacs snakemake-mode. The base URL for MELPA is now melpa.org
https://melpa.org/#/snakemake-mode
https://www.reddit.com/r/emacs/comments/2k2kmv/melpamilkboxnet_is_now_melpaorg/
https://groups.google.com/g/Snakemake/c/H8i7JtPmyoc?pli=1
> docs: update URL to emacs snakemake-mode

- snakemake/logging.py
While using the `--log-handler-script` option, a lot of info is provided but time info is missing.
In this PR, I've added a timestamp to each log entry.
Not sure if possible, but it would also be nice to have the job duration when `level == job_finished`.
> feat: Added timestamp to each log message

- snakemake/caching/__init__.py
- snakemake/caching/local.py
- snakemake/workflow.py
- tests/test_cache_multioutput/Snakefile
- tests/tests.py
> fix: proper error message when defining cache eligibility for rules with multiple output files and no multiext declaration.

- snakemake/notebook.py
- snakemake/report/__init__.py
Closes #1351.
Also fixed report generation with notebooks containing wildcards or params.
> fix: Draft notebook filename with wildcards and params.

- docs/snakefiles/configuration.rst
- Is it `configfile` or `configfiles` ? 
- pattern `--config` of Markdown seems to be ``--config`` in RST (I will double check that with my previous commit)
- [API](https://snakemake.readthedocs.io/en/latest/api_reference/snakemake.html#api-reference-snakemake) references`configfiles`, but does not describe CLI parameter
it's only about the docs
> docs: Command line arguments for configuration files

- docs/executor_tutorial/tutorial.rst
Minor documentation fix. Link was broken in 9b012394eb793a38a4c0752766f3da991a255674
> docs: fix broken link in executor_tutorial/tutorial.rst

- snakemake/deployment/conda.py
- tests/test_deploy_hashing/Snakefile
- tests/test_deploy_hashing/a.post-deploy.sh
- tests/test_deploy_hashing/a.yaml
- tests/test_deploy_hashing/b.yaml
- tests/tests.py
When including post-deploy scripts the environment hash will not take the scripts into account.
In case different rules have conda environment files with identical content but different (or non) post-deploy scripts they will activate the same environment based on the env file content.
To fix this the hash of each environment will now also include the content of post-deploy scripts.
> fix: consider post-deploy script for env hashing  

- docs/snakefiles/deployment.rst
- tests/test_io.py
This commit also includes some minor text editing.
add sentence about workflow template to docs
> docs: add sentence about workflow template to docs

- snakemake/remote/XRootD.py
Change the way `XRootDHelper` checks the existence of a URL to accommodate for object store, where listing a directory does not make sense. 
This was mentioned in an old issue: https://github.com/snakemake/snakemake/issues/809
Until `v6.7.0`, `exists` would throw an exception, as described in the issue. 
From `v6.8.0`, this PR https://github.com/snakemake/snakemake/pull/1017 changed the behavior, and `exists` would unduly return `False`
This PR uses `stat` call instead of listing the directory (adding @chrisburr as origin author, as he probably had a reason to do it this way)
A side effect is that `exists` also works for directories, while before it would return always `False` (this can easily be changed if it is an issue, these are the comments in the code).
Not sure how you go about …
> fix: XRootDHelper.exists supports non posix filesystem (object store)

- docs/getting_started/installation.rst
The word "to" was missing. I also think the word "need" reads better than "have" in this setting.
> fix: typo in installation.rst

- snakemake/deployment/conda.py
- snakemake/rules.py
> fix: fix assertion error in conda env file spec when applying wildcards (thanks @ddesvillechabrol)

- snakemake/rules.py
Hi, this is in relation to #1367.
Summary of changes:
- Modify function 'check_output_duplicates' to check for empty value
- Complete docstring
- Add period at the end of raise message
Fixes the aforementioned issue. I ran pytest (skipped `test_tibanna` which was failing due to lack of credentials) and all tests passed.
> fix: don't raise WorkflowError when entry is empty

- snakemake/linting/__init__.py
- snakemake/logging.py
It is considered to be an antipattern the usage of mutable types as a default argument of the function.
https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html
> fix: avoid mutable default argument

- snakemake/workflow.py
After updating snakemake to its current version, the following code fails with `TypeError: 'NoneType' object is not iterable`:
```python
workflow = Workflow(snakefile=snakefile)
```
This PR attempts to fix that issue.
> fix: fix None type error when invoking Workflow object manually

- snakemake/modules.py
- snakemake/report/__init__.py
- snakemake/workflow.py
> fix: skip global report caption when using a module

- snakemake/unit_tests/__init__.py
- snakemake/unit_tests/templates/ruletest.py.jinja2
- tests/test_github_issue1384/Snakefile
- tests/tests.py
> fix: fix issue when generating unit tests for rules with directory output

- docs/tutorial/setup.rst
> docs: fix tutorial setup instructions for MacOS.

- snakemake/workflow.py
- tests/test_conda/Snakefile
PR to resolve #798. Convert pathlib to string before running checks on conda_env.
> fix: convert conda env to string before checks

- snakemake/dag.py
- snakemake/jobs.py
- snakemake/logging.py
- snakemake/workflow.py
> fix: warn on non-file-modification-date changes like params, code, or input files

- docs/snakefiles/deployment.rst
- docs/tutorial/basics.rst
- docs/tutorial/setup.rst
Fix missing newlines between code:: console and code block (tutorial/setup.rst/snakefiles/deployment.rst).
Fix broken link to gitpod. (from tutorial/basics.rst to tutorials/setup.rst).
Remove some leading spaces (various places).
> docs: Fix problems with code blocks and broken internal link.

- doc-environment.yml
Bumped Python to 3.7
Removed docutils constraint on version 0.12 (resulted in unresolved dependencies)
Added missing dependency myst-parser
> build: Fix conda dependency file for documentation build

- snakemake/__init__.py
Before, Snakemake was complaining that cores or jobs aren't defined, but --cleanup-metadata just deletes the metadata and does not execute anything.
> fix: do not require --cores or --jobs to be set when --cleanup-metadata is used.

- docs/snakefiles/rules.rst
> docs: template rendering examples and available variables

- docs/project_info/faq.rst
Add FAQ entry on relative path interpretation.
> docs: explain relative path interpretation

- snakemake/sourcecache.py
Fixes #1435. The temp folder chosen before could lead to unexpected behavior in clusters where the temp folder changes across nodes. Further it could  have caused issues where the folder is not writable.
> fix: more robust place for runtime source file cache

- LICENSE.md
- README.md
- docs/conf.py
Set copyright year to 2022 in license file and readme. 
Update year automatically for online documentation.
> docs: update copyright year

- snakemake/__init__.py
- snakemake/workflow.py
> fix: provide proper error when using immediate submit in combination with checkpoint jobs.

- snakemake/executors/__init__.py
Fixing an issue where actually sys.stdout should have been used.
> fix: small bug in snakemake.executors

- snakemake/sourcecache.py
Needs an mtime implementation for all kinds of source files.
> fix: set mtime for cached source files [WIP]

- snakemake/rules.py
- tests/test_github_issue1396/Snakefile
- tests/test_google_lifesciences.py
> fix: failure to properly apply default remote prefix in combination with the unpack marker

- docs/snakefiles/rules.rst
- Fixed a typo as mentioned in https://github.com/snakemake/snakemake/issues/1113
- Fixed a grammar mistaske in the scatter-gather workflow section
(Very small changes to get acquainted with the contribution process and project setup)
> docs: Fix typo and grammar mistake in scatter-gather section.

- snakemake/executors/__init__.py
- tests/test_cluster_statusscript_multi/Snakefile.nonstandard
- tests/test_cluster_statusscript_multi/sbatch
- tests/test_cluster_statusscript_multi/status.sh
- tests/tests.py
**Note:** This is a resubmission of my previous PR #977. I closed it temporarily and rebased it onto main, but since I force pushed it I couldn't re-open it. I apologize for the extra noise. This is a minor fix that comes with a test, and I think is a nice complement to the recent cluster feature updates (e.g. `cluster-cancel`) and the Slurm overhaul in PR #1015 
---
I'm a first-time contributor but long-time user, so I wanted to start by saying: Snakemake is awesome! I really appreciate all the effort to develop and maintain this awesome resource.
I am trying to use `--cluster-status` with a multi-cluster Slurm setup. To check the status of the job, both `sacct` and `scontrol` require the jobid and the name of the cluster. When I use the `sbatch` option `--parsable`, it returns both in …
> fix: quote jobid passed to status script to support multi-cluster Slurm setup

- setup.py
- snakemake/sourcecache.py
> fix: implement lock-free source file caching. This avoids hangs on network file systems like NFS.

- snakemake/__init__.py
- snakemake/dag.py
- snakemake/workflow.py
> fix: always deploy conda envs in main process when assuming a shared file system (fixes issue #1463)

- snakemake/jobs.py
- tests/test_github_issue1469/Snakefile
> fix: do not wait for named or containerized conda envs

- setup.py
Warehouse now uses the project_urls provided to display links in the sidebar on [this screen](https://pypi.org/project/requests/), as well as including them in API responses to help the automation tool find the source code for Requests.
Example: [pypi.org/pypi/requests/json](https://pypi.org/pypi/requests/json)
Docs: [packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls)
> chore: add GitHub URL for PyPi

- docs/getting_started/installation.rst
Adding infos to the docs, with the commands to quickly install a particular state of the snakemake repository for testing purposes.
> docs: add install info of development (git) version to docs

- snakemake/remote/GS.py
> fix: mtime inventory for google storage was accidentally setting a float instead of a proper mtime object

- setup.py
- snakemake/common/__init__.py
- tests/testapi.py
**tl;dr** As of fd5daaeff070f9987dba411a0f5262c533a2f666, snakemake requires Python 3.7. This PR updates any reference to previous versions
I came to the GitHub repo to determine the minimum required Python version to run Snakemake, and I quickly got confused. The README displays Python 3.5:
But `setup.py` clearly requires Python 3.7+
https://github.com/snakemake/snakemake/blob/5f7170e095a961ce11ac87467a20879dc4f220f4/setup.py#L14-L16
I was going to simply update the metadata
https://github.com/snakemake/snakemake/blob/5f7170e095a961ce11ac87467a20879dc4f220f4/setup.py#L109
But I saw in commit 0357911cc919a1289004bad9144e75d2880665c7 that the minimum required version is specified in multiple other places. This PR is my attempt to update the code and tests to remove any reference to Python …
> fix: update for minimum of Python 3.7

- snakemake/deployment/conda.py
Fixes #1496
I changed the print output when using a post-deploy script to use `os.relpath` instead of `pathlib.Path.relative_to` since 
the pathlib variant fails when the conda-env is outside of the .snakemake directory. 
So I think existing test cases should cover it (Also since a conda environment would have to be created outside of the working directory I have no clue how one would write a test case for this.)
> fix: Replaced pathlib relative_to with os.relpath

- snakemake/executors/google_lifesciences.py
- snakemake/executors/google_lifesciences_helper.py
This makes slight changes to the google_lifesciences_helper.py script to make GSL logs more helpful. These changes make GSL logs overwritten if present, saved per job_id to allow separation between multiple instances of the same rule, and have a .txt type so that they can be viewed easily in the browser.
See also #1485
> fix: in google live science backend, save multiple logs per rule name and overwrite existing logs

- docs/snakefiles/deployment.rst
> docs: Clarify the use of conda with notebook directive

- snakemake/common/__init__.py
- snakemake/common/tbdstring.py
- snakemake/exceptions.py
- snakemake/jobs.py
- snakemake/rules.py
- tests/test_incomplete_params/Snakefile
- tests/tests.py
> fix: more robust handling of incompletely evaluated parameters (any interaction with them will result in a string <TBD> now).

- snakemake/deployment/conda.py
This modification aims to fix issue #749 and #520. I use the resolution coming from the issue #520.
As a reminder, the problem is that Singularity's logging messages interfere with the verification of the conda version that is done. This solution of @mariafiruleva seems to solve the problem and does not present any side effects
> fix: fix singularity logging messages causing conda fail

- misc/vim/syntax/snakemake.vim
Add `container` to list of directives for syntax highlighting.
Added `container` directive to syntax highlighting.
NA, only affects vim file; tested locally.
> chore: add container to vim syntax

- snakemake/workflow.py
> fix: proper error message in case of missing git when checking for source files

- snakemake/deployment/conda.py
> fix: obtaining conda prefix from older Python versions

- CHANGELOG.md
- snakemake/dag.py
- tests/test_pipe_depend/Snakefile
- tests/tests.py
> fix: throw error message in case of target rule that depends on a pipe.

- snakemake/dag.py
- tests/test_github_issue1542/Snakefile
- tests/tests.py
> fix: do not remove existing temp files in case of dryrun

- snakemake/persistence.py
- snakemake/workflow.py
- tests/tests.py
> fix: report warning and possible cause if metadata cleanup fails

- snakemake/jobs.py
- snakemake/scheduler.py
- tests/test_github_issue1550/Snakefile
- tests/tests.py
> fix: always recalculate job resources before job is scheduled as input might have changed or not have been present initially

- snakemake/rules.py
- tests/test_github_issue1389/Snakefile
- tests/tests.py
> fix: proper error message if resource types do not match

- snakemake/sourcecache.py
> fix: properly use retry mechanism in source cache

- snakemake/report/__init__.py
> fix: allow category and labels functions for report marker to return None

- docs/snakefiles/rules.rst
- snakemake/parser.py
- snakemake/report/__init__.py
- snakemake/rules.py
- snakemake/template_rendering/__init__.py
- snakemake/workflow.py
> fix: support multiple input files for template_engine rules

- snakemake/path_modifier.py
> fix: multiext prefix computation in case it is used within a module that defines an additional prefix

- snakemake/executors/common.py
Fixes issue #1615 
A dictionary will return true when using _not_iterable_ from snakemake.io. The elif condition is never reached/true in the original code. Swapping them will cause dictionaries to be formatted as expected by snakemake.
I'm not sure how to test this, or if i break any other functionality by changing this.
> fix: issue 1615 - Switch formatting condition for dictionary

- README.md
- snakemake/dag.py
When I re-start a workflow with checkpoints, I get spammed with an enormous amount of `updating job` prints. I think those prints are supposed to be hidden? The other updating job prints are logged under the debug logger:
https://github.com/snakemake/snakemake/blob/main/snakemake/dag.py#L1536
https://github.com/snakemake/snakemake/blob/main/snakemake/dag.py#L1618
> fix: remove redundant print

- docs/snakefiles/remote_files.rst
- snakemake/remote/zenodo.py
> feat: enable restricted access support in zenodo remote provider

- snakemake/workflow.py
> fix: fix spurious duplicate rule exception when requesting a specific rule from a module that contains local rule inheritance

- snakemake/logging.py
- snakemake/remote/zenodo.py
> fix: fixed permission issues when using zenodo remote provider to access restricted depositions

- .github/workflows/main.yml
- Dockerfile
- snakemake/deployment/conda.py
> fix:  fail with error if conda installation is not set to strict channel priorities

- Dockerfile
Otherwise, setting the docker home directory would lead to channel priority not being considered properly.
> fix: set channel priority in container system wide

- snakemake/dag.py
> fix: more robust calculation of number of jobs until ready for execution

- snakemake/dag.py
Fixes an issue where checkpoints trigger unnecessary reruns of downstream functions that has been introduced with the provenance based rerun triggers of Snakemake 7.8.
> fix: fixed bug in needrun computation of jobs downsteam of checkpoints

- snakemake/deployment/singularity.py
> fix: allow apptainer as a successor to singularity.

- snakemake/workflow.py
**Passes rerun-triggers to subworkflow.** Also passes resources.
> fix: pass triggers and resources to subworkflow

- .github/workflows/conventional-prs.yml
- .github/workflows/main.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- .github/workflows/release-please.yml
- pyproject.toml
- setup.py
This PR introduces a `pyproject.toml` file described by [PEP 518](https://peps.python.org/pep-0518/), and uses PyPA's [build](https://github.com/pypa/build) to check building the package (sdist and wheel files).
In addition, lots from `setup.py` is removed or simplified:
- E.g. first few lines are not needed for Python 3, which is UTF-8 by default and has a print function
- Dunders `__author__` etc are not normally used in this file
- Remove `setuptools` check, since this is a build requirement specified in the correct place (`pyproject.toml`)
- Remove Python version check, since this is done with setuptools' `python_requires`
- Note that lots of the static metadata from `setup.py` can be moved to either `setup.cfg` or `pyproject.toml`, but not done in this PR
> chore: add pyproject.toml to use setuptools features

- snakemake/deployment/conda.py
> fix: only display a warning in case of non-strict channel priorities

- snakemake/persistence.py
> fix: add lock free mechanism for avoiding race conditions when writing persistence information; consider corrupt metadata records as non-existent

- snakemake/script.py
Fixes #1045 which was caused when `np.bool_` type was used for boolean values and was slipping through the instance checking and raising an error. 
* [x ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
> fix: ensures that REncoder also checks for numpy.bool_ in encode_value

- snakemake/persistence.py
> fix: limit filename length of temporary files generated by the persistence backend (metadata, incomplete markers, etc.)

- docs/executing/grouping.rst
- docs/snakefiles/rules.rst
I discovered a few mistakes in the `.rst` documentation leading to incorrect display. Hopefully this fixes the problems. Is there any way to preview the site before merging?
> fix: Fix technical bugs in resource-scope documentation

- snakemake/executors/__init__.py
> fix: move max_status_checks_per_second attribute setting before the wait thread of cluster backends is started to avoid missing attribute errors

- snakemake/jobs.py
> fix: allow to use {wildcards} for group jobs in cluster config

- snakemake/deployment/conda.py
When running snakemake with micromamba a `CreateCondaEnvironmentException` should be raised (should it really? that is a different story... ;)
However, the code `msg += ("lorem ipsum",) tries to concatenate a str and tuple and causes a TypeError. 
Removing the trailing comma fixes this issue and the error message is successfully created and raised. 
I don't think these are relevant for this simple fix.
> fix: remove superfluous comma causing TypeError in conda-frontend error message

- docs/snakefiles/deployment.rst
- docs/snakefiles/rules.rst
- snakemake/deployment/conda.py
- test.sh
> fix: respect shebang lines in post-deploy scripts (see deployment docs)

- snakemake/script.py
This PR adds a hotfix for bash scripts. I don't know if this is a Bash version issue or not, but when I tried to run a bash script on v4.4.20 (I tested the implementation of bash scripts with v5.1.16) the named variabes were playing up.
Here is an example to illustrate the problem (I've removed `snakemake_config` for brevity)
```bash
#!/usr/bin/env bash
snakemake_input=( [0]="/hps/nobackup/iqbal/mbhall/drprg/paper/results/filtered/illumina/PRJEB25972/SAMEA1101594/ERR2510324/ERR2510324.filtered.fq.gz" [reads]="/hps/nobackup/iqbal/mbhall/drprg/paper/results/filtered/illumina/PRJEB25972/SAMEA1101594/ERR2510324/ERR2510324.filtered.fq.gz" [1]="/hps/nobackup/iqbal/mbhall/drprg/paper/results/download/illumina/run_info.tsv" [run_info]="/hps/nobackup/iqbal/mbhall/drprg/paper/results/download/illumi …
```
> fix: declare associative arrays in bash scripts

- snakemake/common/__init__.py
- snakemake/io.py
> fix: fixed typos

- snakemake/executors/__init__.py
- tests/test_kubernetes.py
- tests/test_kubernetes/Snakefile
k8s supports adding ephemeral storage (e.g. node-local SSDs) to the working directory of the container. However, the size of this working directory isn't configured. This PR maps the `disk_mb` resource to the `ephemeral-storage` k8s Allocatable.
As an aside, while reviewing this PR, I think I have found a small issue: during the container init code, we are setting the `container.volume.mounts` property twice with single-entry lists, rather than once with a list of two mounts as their API seems to want. Is my reading correct, and this is a bug? If so, I'll quickly fix it.  https://github.com/snakemake/snakemake/blob/a1e49b6f290daeb2012575ab3a85ca72cfe42747/snakemake/executors/__init__.py#L1855-L1860
> fix: request disk_mb resource from k8s

- snakemake/persistence.py
> fix: fix falsely triggered reruns if input files are obtained via workflow.source_path()

- snakemake/script.py
- tests/test_script/Snakefile
This PR allows the `script` directive to accept a `pathlib.Path` object.
> fix: allow script directive to take pathlib Path

- snakemake/executors/__init__.py
As described in the body of PR https://github.com/snakemake/snakemake/pull/1858, there's a typo whereby the property `container.volume_mounts` is overwritten, rather than appended to.
> fix: k8s container volume mounts as list

- tests/test_kubernetes.py
- tests/test_kubernetes/Snakefile
> fix: reduce resource requirements for kubernetes tests

- setup.py
- snakemake/remote/__init__.py
- snakemake/sourcecache.py
- test-environment.yml
This implements the suggestion in https://github.com/snakemake/snakemake/issues/1776.
Replaces the `retry` dependency with the compatible maintained fork `reretry`.
*The dependency is drop-in compatible, so existing tests and documentation should not need to be changed.*
> refactor: Replace “retry” dependency with “reretry”

- snakemake/executors/__init__.py
Fix #1698 exception tracebacks in run: blocks are sent to /dev/null, making rules hard to debug
I have created a text based on #1881 but I don't see how I can test that the error message is printed out correctly to a log.
> fix: Add back logging of run directives

- snakemake/dag.py
As described in #1754 and demonstrated there with a minimal example, not all temp files are cleaned up when certain workflows containing "job groups" are run on the cluster. The issue does not occur when running the same workflow locally, in which case the group assignments are ignored, as the purpose of groups is to mark different jobs to be executed on the same cluster node.
This PR fixes the issue. See the problem analysis in [this comment](https://github.com/snakemake/snakemake/issues/1754#issuecomment-1192675070) for details. Essentially, the `job` argument to `dag.DAG.finish()` was being reused as a local variable inside the method. So when `job` was a group of jobs, it would only handle temp files for the last job in that group. We fix that by calling `handle_temp()` explicitly for …
> fix: Handle temp files for all jobs in a group.

- docs/executor_tutorial/flux.rst
After seeing it live - here are some small tweaks to make it better!
- We do not have more than one step, so it does not make sense to include Step 1.
- The spacing on the first bulleted list is off because I think I used `*` instead of `-`.
- I added an actual link to the Dockerfile in examples.
- The flag in the list was missing the correct quotes
- The first sentence will read/ look better just as "Flux Framework" as part of the sentence instead of in parentheses.
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
> docs: small tweaks to flux documentation

- docs/project_info/faq.rst
- docs/snakefiles/rules.rst
The code example for the question "**How does Snakemake interpret relative paths?**" included a typo: It used `workflow.get_source(...)` instead of  `workflow.source_path(...)`.
**Thus**: Changed `workflow.get_source(...)` to `workflow.source_path(...)`.
> docs: various little fixes

- snakemake/executors/__init__.py
- snakemake/scheduler.py
- tests/test_immediate_submit/README.md
- tests/test_immediate_submit/Snakefile
- tests/test_immediate_submit/expected-results/output/all
- tests/test_immediate_submit/slurm/config.yaml
- tests/test_immediate_submit/slurm/get_jobid.sh
- tests/test_immediate_submit/slurm/sbatch.sh
parameter `--immediate-submit` is expected to [submit all jobs to the cluster instead of waiting for present input files](https://snakemake.readthedocs.io/en/stable/executing/cli.html?highlight=immediate#CLUSTER). However, as tested in the system, nothing changed compared to "run without this flag".
Detailed discussions can be found in #1865 and #1715. Briefly, it is caused by a hotfix for googlelifescience API handling.
> fix: fix `--immediate-submit`

- snakemake/dag.py
* fixes #1892
* fixes #1891
Thanks to @ftabaro for pointing me to the problem and providing an initial solution (https://github.com/snakemake/snakemake/pull/1893).
> fix: ensure that rule name string instead of object is passed to tabulate package

- snakemake/rules.py
Fixes #1891 and #1892. The issue is that the [`__eq__` method of `Rule`](https://github.com/snakemake/snakemake/blob/274d613fd27b632d5bbe4c6fe55a82262d6b2dec/snakemake/rules.py#L1221) implicitly expects `other` to be an instance of `Rule` as well. Thus, any comparison of a `Rule` instance to any non-`Rule` object leads to an `AttributeError`. This is a more general fix than #1893.
> fix: Comparison of rules and non-rule instances

- snakemake/io.py
Previous NamedList performance is optimized for integer/slice (list) access, but very slow when using string indices. 
With this change, both types of access are approximately equally fast and average performance (assuming equal number if integer and string accesses) is improved.
**Note:** If you assume that integer/slice (list) access is the norm and named access is rare (less than 7 times as frequent as list accesses), then please ignore this pull request. In my workflow, named accesses are much more frequent, so this change lead to a major performance improvement.
Performance comparison below are from accessing a named list with 1e4 list components and 1e4 named components, attempting 1e4 accesses on my system. Multiple attempts on a different system confirmed similar numbers.
Original …
> perf: Average NamedList __getitem__ performance improvement

- snakemake/io.py
In #1869 I added the ability to use a `pathlib.Path` object in the `script` directive. When generating a report where a rule has a Path in the script directory, this function was causing snakemake to error as it assumes the path is a string. This PR makes it explicitly a string.
> fix: allow report generation to handle pathlib objects

- snakemake/deployment/conda.py
`conda create --no-shortcuts` is only valid on windows. The option does not exist on other OSes. This fixes the regression introduced in #1046
See https://github.com/conda/conda/blob/32b958df05e5fab04254ed2af9044ea99f5f13f1/conda/cli/conda_argparse.py#L1827-L1837
> fix: conda create --no-shortcuts absent on Linux/MacOS (regression from #1046)

- misc/vim/syntax/snakemake.vim
> snakemake.vim: add envmodules keyword

- docs/snakefiles/rules.rst
This just removes a single period in the documentation section about the multiext function, so that this, with a redundant period:
```
expand("some/plot.{ext}", ext=[".pdf", ".svg", ".png"])
```
becomes this, matching the expected output:
```
expand("some/plot{ext}", ext=[".pdf", ".svg", ".png"])
```
Fixes #1012.
> fix: remove redundant dot in expand call in multiext documentation

- snakemake/persistence.py
The value of `os.pathconf(self._incomplete_path, "PC_NAME_MAX")` is cached in an attribute `Persistence._max_len` -- this avoids repeatedly querying the operating system for the same configuration information every time `marked_incomplete()` is called on a file/job output. (Note: this will dramatically speed up Snakemake DAG building on compute clusters where `os.pathconf()` is slow to return and the number of files checked for incompleteness is very large.)
> perf: cached os.pathconf() call in _record_path()

- snakemake/jobs.py
- snakemake/logging.py
> fix: show input files on job error

- snakemake/executors/__init__.py
The option `--keep-incomplete` was not correctly forwarded in the case of cluster execution, causing jobs to clean up output files in case of failure, despite the main snakemake process being called with `--keep-incomplete`. Below is a MWE:
```snakefile
rule test:
output:
"file.out"
shell:
"touch {output[0]}"
```
Run with `snakemake -j1 --cluster "bash -x" --keep-incomplete file.out` to see that `--keep-incomplete` is absent from the `snakemake` call in the generated jobscript.
I've looked at adding a regression test, but I'm not sure how to do that in the snakemake tests, which is why the box below is unchecked. Any advice is appreciated.
> fix: forwarding --keep-incomplete to cluster executor

- snakemake/notebook.py
This should fix #718. The cleanup routine after editing a notebook would add the `"outputs"` attribute to all cells in the notebook, which would cause the JSON validation of nbconvert to fail for cells where no output is expected.
I've also added a cleanup of the `"execution_count"` property, which should make SCM management of the notebook easier (execution count of cells is prompt to frequent changes in interactive sessions). I can remove it if that change is superfluous.
Finally, I think #1032 can be safely closed, I have not encountered it with recent versions of snakemake.
> fix: json validation error with markdown cells

- docs/snakefiles/remote_files.rst
- snakemake/remote/gridftp.py
- add a keyword(`streams`)to GridFTP remote provides to specify the number or disable the usage of multiple data streams. This can be handy when the system does not support multiple streams. The keyword can be set in the provider and remote object(remote object is prioritized).
- Also removes some outdated info about the retry keyword for the gfal and GridFTP provider
> feat: add  keyword to gridftp remote provide to specify the number or disable usage of multiple data stream

- snakemake/persistence.py
- tests/test_github_issue1882/Snakefile
- tests/tests.py
Fixes issue #1882: WorkflowError: Metadata can't be created as it already exists (Windows)
The underlying cause of the problem is that `os.rename` was used to overwrite the target file. Unfortunately, it has a different behavior under Unix/Linux (overwrites target) and Windows (fails). `os.replace` is an alternative to `os.rename` that simulates the  Unix behavior.
The required change is extremely small (commit 4ad1ab1) and I have also added a test case covering it (commit e12955f).
> fix: issue #1882 WorkflowError: Metadata can't be created as it already exists (Windows)

- snakemake/executors/common.py
- tests/common.py
- tests/tests.py
ResourceScopes, a subclass of UserDict (not dict), was getting parsed as a regular iterator, not a dict, so only the keys were being passed on.
Resolves #1968
> fix: Correctly parse UserDicts in executors

- snakemake/parser.py
- tests/test_parsing_terminal_comment_following_statement/Snakefile
- tests/tests.py
This occurred when a file-terminating comment was followed a keyword, as the closing parentheses would be put on the same line as the comment and not seen by the parser, leading to a syntax error.
Fix by adding a newline before the closing parentheses. Adds a test case based on the original report.
Resolves #1943
> fix: parsing error when last line is comment

- snakemake/dag.py
- snakemake/jobs.py
- tests/test_group_jobs_attempts/Snakefile
- tests/test_group_jobs_attempts/qsub
- tests/tests.py
Attempts was getting updated on the group job, but not getting updated on the group job's member jobs. This prevented the member job resources calculations from being updated, preventing the correct functioning of resource lambdas in the group job context.
This propagates the update to the members and adds a test
Resolves #2045
> fix: propagate attempt count from group to subjobs

- snakemake/dag.py
- tests/test_touch_with_directories/Snakefile
- tests/tests.py
When using the --touch flag, missing files are disregarded by dag.check_and_touch_output. This same function also checks that directory outputs are correctly labelled with `directory()` and vice-versa. This test was failing when the file was missing.
This patch skips the test when the file is missing.
Resolves #211
> fix: skip type checks of missing dir in touch mode

- docs/snakefiles/deployment.rst
`Snakefile` after broken link was not highlighted correctly.
Compare to current deployment [link](https://snakemake.readthedocs.io/en/v7.19.1/snakefiles/deployment.html) (`7.19.1`)
> fix: :bug: - fix hyperlink

- snakemake/__init__.py
I noticed this typo in the documentation, but could only find the text in the actual source code. I assume something is copying help text into the docs, but if it's hiding somewhere else, please let me know.
> docs: Fix typo in SLURM help text

- snakemake/logging.py
> fix: make `--show-failed-logs` handle empty log files

- snakemake/__init__.py
Config values such as `--config arg=` were getting parsed as `None` by the `yaml_base_load` parser and failing the subsequent assertion `assert v is not None`. Instead, check first if val is a blank string.
This fix assumes we want blank strings to be a valid option for `--config` args, which seems reasonable to me. Otherwise, we need to explicitly check for blank strings and throw a better error.
Resolves #1903
> fix: correctly parse empty values in config cli

- snakemake/__init__.py
- snakemake/exceptions.py
- tests/tests.py
When running in any no-exec mode (e.g. `--dag`, `--report`), `--jobs` was getting left as a string, leading to workflow errors.
This PR takes the opportunity to refactor the jobs and cores parsing code, which was very convoluted. Parsing is split into three basic possibilities: `no_exec` mode, `non_local_exec` mode, and `local_mode`. `jobs` and `cores` are both set appropriately given the context.
A test is provided to test the new parsing function.
Resolves #1589
> fix: Fix handling of --jobs in no-exec state

- setup.py
Adds python versions 3.8-3.11 to classifier list
Brought to my attention by #1990: this should cause the badge to update with the correct versions.
> fix: Update list of python versions in classifiers

- snakemake/executors/slurm/slurm_submit.py
This would fix #2014 since the short argument is the same (`-D`) even if the long argument changed from `--workdir` to `--chdir` after Slurm 17:
https://slurm.schedmd.com/archive/slurm-17.02.0/sbatch.html
https://slurm.schedmd.com/sbatch.html
> fix: use short argument name for `--chdir` for compatibility with Slurm <=v17

- snakemake/jobs.py
If I understand the mechanics correctly, jobs in job groups executed on clusters get "postprocessed", and as part of this their output files are touched. However, the order in which this happened was not necessarily a topological order, meaning that output files of dependent rules could be touched in the "wrong" order. See https://github.com/snakemake/snakemake/issues/789
This simple change just ensures that jobs are post-processed in topological order, which should solve the above issue.
If desirable, I could also writing a test for the above behaviour to catch potential future issues.
> fix: Postprocess job groups in toposorted order for correct touch times

- snakemake/persistence.py
> fix: more robust encoding of params in persistent metadata storage. This way, pandas parameters do not lead to spurious rerun triggers.

- snakemake/dag.py
The new version uses scandir instead of listdir, so it uses an iterator-based approach to detect whether a directory is empty or not. 
The execution time of the old version depended on the number of files in the directory, while the new version should be more or less constant.
200K files in a directory mounted over nfs:
timeit (new version):
```
if os.path.exists(io_dir):
with os.scandir(io_dir) as i:
if next(i, None) is None:
```
--> 1.98 ms ± 22.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
timeit (old version):
`if os.path.exists(io_dir) and not len(os.listdir(io_dir)):`
--> 50.4 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
No new function was added.
> perf: Improve execution speed of cleanup_workdir (in dag) 

- setup.cfg
This minor edit changes the `long_description_content_type` to `text/markdown`. The current rendering on [PyPI](https://pypi.org/project/snakemake/7.22.0/) with `text/plain` is fixed width, whereas `text/markdown` should render it more normally.
> fix: use text/markdown for long_description_content_type

- docs/snakefiles/remote_files.rst
- snakemake/io.py
- snakemake/remote/XRootD.py
- snakemake/remote/__init__.py
Support for tokens in the interface with XRootD.
As the tokens used by EOS at CERN are URL parameters, this PR allows adding them when needed (an extra "decorator" parameter has been introduced) 
* [x ] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).
> feat: Add support for tokens in the XRootD interface

- snakemake/executors/__init__.py
Ran into a bug where executing a workflow locally causes a crash with group jobs.
```
if self.workflow.verbose or (job.is_run and not job.is_group()):
^^^^^^^^^^
AttributeError: 'GroupJob' object has no attribute 'is_run'
```
Swapping the order of the checks fixes this issue; not sure why the CI didn't catch this bug.
> fix: is_run error with local, group jobs

- docs/snakefiles/modularization.rst
Add explicit warning to avoid naming imported module with `workflow` (keyword). This is based on https://stackoverflow.com/a/75543511/10693596
> docs: Update modularization.rst

- snakemake/io.py
…bdirectories is properly resolved during write-protection
This is a very small change that ensures paths to files in subdirectories are properly resolved during write-protection of `directory()` outputs.
> fix: #2130 by patching the protect() method so the path of files in subdirectories is properly resolved during write-protection

- .github/workflows/main.yml
- setup.cfg
- test-environment.yml
Closes #2134, speeds up DAG resolution through pulling in the latest `toposort` that leads to a 200x speedup of the `toposort()` function for larger DAGs, see:
https://gitlab.com/ericvsmith/toposort/-/merge_requests/4
> fix: require toposort >= 1.10

- .github/workflows/main.yml
- snakemake/caching/local.py
- snakemake/persistence.py
- snakemake/sourcecache.py
This way, multiple users can more conveniently work on the same workdir.
> fix: ensure user and group rw permissions for metadata files and source cache

- docs/executing/cluster.rst
- docs/snakefiles/rules.rst
- snakemake/common/__init__.py
- snakemake/jobs.py
> feat: limit the number of input/output files in job properties

- snakemake/rules.py
- `sre_constants` is deprecated, the import statement was updated accordingly
The `re` module sources are being reorganized, see more information: https://github.com/python/cpython/issues/91308
Small fix accommodates changes for all python versions.
> fix: `sre_constants` import because of deprecation

- snakemake/executors/slurm/slurm_submit.py
- snakemake/scheduler.py
This PR changes two things:
1. Previously, checking `active_jobs` was only initiated after sleeping for `1/max_status_checks_per_second` seconds, which meant a minimum sleeping time of 30 seconds. This sleeping interval is now set to a fixed 30 seconds. However, one idea could also be to turn this into a new variable for the generic executor, and expose it to the user via a command-line argument -- it is also manually set for other executors (e.g. the google executor), and might require fine-tuning for specific workflows and/or clusters.
2. Previously, a `max_status_checks_per_second > 1` specified by the user was set down to `max_status_checks_per_second = 0.03` (no clue why there were different values in the comparison and the final setting) and the default value was also `0.03`. This …
> fix: better job status queries for slurm executor 

- snakemake/script.py
> fix: get python version for script environment in a backwards compatible way that works down to python 2.7

- snakemake/linting/rules.py
Minor PR to fix typos I saw while running `snakemake --lint`
> docs: fix minor typos in a linting rule

- tests/test_schema.py
- tests/test_validate/config.schema.yaml
- tests/test_validate/samples.schema.yaml
Prevents DeprecationWarning caused by using an old draft of JSON schema when running tests. updated JSON schema and use https.  
Run into this issue while sorting out documentation about testing.
> fix: prevents DeprecationWarning caused by using old  draft of json schema

- snakemake/logging.py
Limit the maximum length of the decorations around the logfile output of a failed job (when `--show-failed-logs` is given) to 80.
Fixes #2101.
> fix: limit length of failed logs decorations

- docs/tutorial/setup.rst
Change the link for downloading the snakemake-tutorial materials to a version-agnostic link that always gets the latest release. Inspired by https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8.
> docs: Change snakemake-tutorial download link to always be the latest

- snakemake/__init__.py
Fix typos in `__init__.py` that show up when you run `snakemake --help`
> docs: fix typos in --help

- snakemake/parser.py
Update `parser.py`  so that the help message is more helpful when a rule contains multiple run/shell/script/notebook/wrapper/template_engine/cwl keywords, which is not allowed.
> docs: Improve error message when rule contains multiple run/shell/script/notebook/wrapper/template_engine/cwl keywords

- snakemake/executors/slurm/slurm_jobstep.py
- snakemake/executors/slurm/slurm_submit.py
This is a follow-up pull request to #2136 , providing a more thorough solution to putting less strain on the slurm cluster system with job status queries.
The solution suggested here:
* assigns the same UUID4 as the job name during `sbatch` job submission for all jobs during a run of snakemake -- this goes back to [an idea by Sean Maxwell on the `slurm-users` mailing list](https://lists.schedmd.com/pipermail/slurm-users/2023-February/009713.html)
* uses `sacct` as the job status query command, as this [will put less strain on `slurmctld` and instead query the `slurmdbd`](https://github.com/snakemake/snakemake/pull/2136#issuecomment-1442618490) and we assume that any reasonable cluster setup will have at least basic [job accounting](https://slurm.schedmd.com/accounting.html) set up
* uses …
> fix: slurm batch job status queries

- snakemake/io.py
- snakemake/persistence.py
- snakemake/workflow.py
> fix: always make sure that the original path of source cached files is properly passed into metadata persistence records

- docs/project_info/contributing.rst
As mentioned in  #2204 Contributing guide still refers to `nosetest`.
> docs: replace `nosetest` with `pytest`

- snakemake/dag.py
This PR fixes #2216, by using the job rule name as derived in the dag.
I am not entirely sure what the persistence class does here, but I guess it somehow caches the jobname in the .snakemake directory when the rule is run. This probably leads to incorrect summaries before the rules have been cached, which does not seem like the intended behavior of the summary option.
> fix: Use `job.rule.name` attribute to fill rule field in summary

- docs/snakefiles/writing_snakefiles.rst
1. Add `priority` directive to Snakefile syntax specification (see https://snakemake.readthedocs.io/en/stable/snakefiles/writing_snakefiles.html)
2. Add Wikipedia link for extended Backus-Naur form (EBNF).
> docs: Update workflow syntax with priority directive

- snakemake/__init__.py
- snakemake/_version.py
- snakemake/benchmark.py
- snakemake/cwl.py
- snakemake/dag.py
- snakemake/exceptions.py
- snakemake/io.py
- snakemake/jobs.py
- snakemake/logging.py
- snakemake/notebook.py
- snakemake/parser.py
- snakemake/path_modifier.py
- snakemake/persistence.py
- snakemake/resources.py
- snakemake/rules.py
- snakemake/scheduler.py
- snakemake/script.py
- snakemake/shell.py
- snakemake/sourcecache.py
- snakemake/utils.py
- snakemake/workflow.py
- snakemake/wrapper.py
Python support f-string since python 3.6.  Formatting strings with f-string has an higher readablity due to easier and more compressed syntax and is a tiny bit faster. This pull request rewrite format() and %s syntax to f-strings. However, there are still places were format is used because it is not straightforward to convert them without risk of breaking code. Most work is done with [ruff](https://beta.ruff.rs/docs/) 
`ruff check --select UP032,UP031,F541  . `
This pull request touches a lot of lines, so this might break other work in progress.
> refactor: format()  and %s replaced by f-strings

- docs/executing/cloud.rst
- docs/executor_tutorial/azure_batch.rst
- snakemake/executors/azure_batch.py
- tests/test_azure_batch_executor.py
- Patches the Azure Batch Executor docs to include instructions for generating an SAS token
- Updates the Azure Batch Executor test to pull docker image from the latest snakemake release
> docs: update docs for azbatch and dockerhub ref

- snakemake/persistence.py
- tests/common.py
- tests/test_azure_batch_executor.py
- previous try catch solution wasn't triggered
- use detecting availability of the module instead
> fix: Detect pandas availability to select serializer

- snakemake/executors/slurm/slurm_submit.py
This changes the format string on the calls to 'sacct' and 'sacctmgr' to allow for long slurm account names.  This fix seems to work on our slurm cluster.
> fix: addressing #2197 by allowing 256 character account names in slurm

- snakemake/deployment/singularity.py
Small fix to solve apptainer 1.1.9-1.el8 issue
```
Traceback (most recent call last):
File "/g/korbel2/weber/miniconda3/envs/snakemake_latest_latest/lib/python3.11/site-packages/snakemake/__init__.py", line 771, in snakemake
success = workflow.execute(
^^^^^^^^^^^^^^^^^
File "/g/korbel2/weber/miniconda3/envs/snakemake_latest_latest/lib/python3.11/site-packages/snakemake/workflow.py", line 919, in execute
dag.pull_container_imgs(
File "/g/korbel2/weber/miniconda3/envs/snakemake_latest_latest/lib/python3.11/site-packages/snakemake/dag.py", line 367, in pull_container_imgs
img.pull(dryrun)
File "/g/korbel2/weber/miniconda3/envs/snakemake_latest_latest/lib/python3.11/site-packages/snakemake/deployment/singularity.py", line 46, in pull
self.singularity.check()
File …
```
> fix: Solve apptainer version issue

- snakemake/deployment/singularity.py
Apptainer and singularity use non-PEP440 version numbers like `1.1.8-1.el8` and `3.10.4-dirty`. packaging.version can not handle these version numbers. To mitigate the issue, a character is stripped away at the end of the string until it is parsable by packaging.version.
Should fix #2319  and #2334
> fix: handle non-PEP440 versions of apptainer/singulariy

- docs/snakefiles/deployment.rst
In Snakemake documentation, the priority of channels is not known to the user in environment definitions. I attempted to make this information explicit in case people with little knowledge of conda have issues with it.
> docs: clarify the channel priority in environment definition deployment.rst

- docs/snakefiles/rules.rst
> docs: note on using checkpoint mechanism only for input function, not for params or resources.

- snakemake/deployment/conda.py
- snakemake/linting/rules.py
- snakemake/linting/snakefiles.py
- snakemake/remote/XRootD.py
- snakemake/sourcecache.py
- snakemake/workflow.py
Fixes warnings of the form:
```
SyntaxWarning: invalid escape sequence '\['
```
Some of these warnings were causing linting test failures on Python 3.12.
Converts several regex pattern strings to raw strings (`r""`) in order to avoid `SyntaxWarning` due to invalid backslash-escape sequences
The changes in the first commit fix test failures on Python 3.12. It’s not immediately clear how I would test the changes in the second commit, although I confirm that they eliminate (non-failure) `SyntaxWarning` messages when byte-compiling the modules.
No documentation changes are required.
> fix: SyntaxWarnings due to non-raw regex pattern strings

- docs/executing/cluster.rst
Fixed a typo in the docs, which lead to confusion.
https://stackoverflow.com/questions/76689646/how-to-set-resources-for-snakemake-rules-running-on-a-slurm-cluster
> docs: fix typo (stackoverflow issue)

- snakemake/remote/FTP.py
- snakemake/remote/SFTP.py
- snakemake/remote/__init__.py
- snakemake/remote/gfal.py
The usage of `allows_directories` was removed in #423, but it is still referenced in the code base.
> chore: Remove references to allows_directories

- snakemake/executors/__init__.py
> fix: print exceptions when job is not a shell job

- docs/snakefiles/rules.rst
The current documentation mentions, within the tutorial:
```
set-threads:
b: 16
to set the memory requirement of rule b to 1000 MB.
```
which is apparently a copy&paste left-over from a similar section within the same document:
```
set-resources:
b:
mem_mb: 1000
to set the memory requirement of rule b to 1000 MB.
```
This request fixes this.
- **does not apply**
- **This is only a documentation change.**
> docs: fix a copy&paste (?) mistake

- docs/tutorial/basics.rst
Atom has been deprecated for quite a while, so we should suggest another editor / IDE. We have been using VS Code quite a bit and are very satisfied with its capabilities for developing Snakemake workflows, so that I think this is a reasonable suggestion. But other suggestions are welcome.
> docs: basics.rst: suggest VS Code instead of deprecated Atom as IDE

- snakemake/__init__.py
> fix: better message about profile usage upon execution

- snakemake/executors/azure_batch.py
> fix: do not overwrite default resources setting in azure batch executor

- snakemake/executors/azure_batch.py
- Removes unnecessary setting of Snakefile in AzBatch executor. This was 1. not necessary, and 2. was causing a failure to resolve the Snakefile path when it was located at `workflow/Snakefile`.
- Since default resources is now included in the command per #2395 , I needed to update the shell quoting so the command doesn't fail because of the parentheses in the default resources. Used the same solution as #2043 and it works nicely.
- Updated the masking regex to be more generic for SAS token possibilities
> fix: unnecessary set Snakefile in AzBatch executor

- Dockerfile
Updates the Dockerfile to use micromamba base image leading to a reduced image build time and image size. Below are the results of building this branch ( tagged 'micro' ) and the main branch ( tagged 'latest' ). 
```
docker build -t snakemake:micro .  0.71s user 0.76s system 2% cpu 59.394 total
docker build -t snakemake:latest .  0.78s user 0.85s system 1% cpu 1:29.04 total
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
snakemake    latest    1f6c690e7e0f   28 seconds ago   1.49GB
snakemake    micro     2fcfd48f0d31   3 minutes ago    1.17GB
```
> build: Dockerfile

- snakemake/dag.py
> fix: ensure that targetjob is always forced. This fixes a bug causing run-directive rules to not being executed even when enforced via e.g. -R.

- docs/executing/cluster.rst
Fix misleading syntax in documentation example. See <https://www.biostars.org/p/9575301/>.
> docs: fix syntax in cluster example

- snakemake/executors/google_lifesciences_helper.py
fix: Previous versions of snakemake had a hardcoded link to the file `snakemake/executors/google_lifesciences_helper.py` which was moved in recent API changes. All previous versions of snakemake are now unable to run the Google Life Sciences executor. This pull request would temporarily add this file back in the "expected" location to provide backward compatibility for existing projects using previous versions of snakemake. This is a temporary fix which can be reverted once GLS is deprecated. #2451
> fix: Restore backward compatibility for Google Life Sciences executor

- .github/workflows/main.yml
- setup.cfg
- snakemake/api.py
- snakemake/cli.py
- snakemake/spawn_jobs.py
- snakemake/workflow.py
- test-environment.yml
- tests/test_api.py
@vsoch this should obviate the need to implement hand-made solutions for uploading source code in each executor plugin
> feat: add functionality for deploying sources if no shared FS is assumed

- docs/snakefiles/rules.rst
Quick fix, there's not a 1.15.0 of `rust-script` so I'm guessing this is the issue rather than the environment.
> docs(rust): Fix typo on rust-script version

- docs/executing/cli.rst
- snakemake/cli.py
> feat: version specific profile config files (profile/config.v8+.yaml with profile/config.yaml as fallback that matches any version)

- docs/executing/cli.rst
- docs/snakefiles/rules.rst
- snakemake/cli.py
- snakemake/resources.py
- snakemake/workflow.py
- tests/test_profile/Snakefile
- tests/test_profile/Snakefile.internal
- tests/test_profile/config.yaml
- tests/test_profile/expected-results/test.out
> feat: allow python expressions in --set-resources

- snakemake/jobs.py
#2511
Using "full" mode of shadow will skip files in symbolic link dirs
* [✔ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [ ✔] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).
> fix: shadow "full" mode ignore symlinks

- setup.cfg
- snakemake/logging.py
This updates the Slack ``--log-service``  feature added in #170.
The ``Slacker`` package is no longer maintained, and legacy slack tokens are no longer generatable.
I've replace it with the officially supported [Slack SDK](https://github.com/slackapi/python-slack-sdk) (see ``setup.cfg``), preserving the original functionality with minimal adjustments.
This has been minimally tested for functionality. However, the original implementation has a couple issues (which this PR **does not** address) - 
1. Lack of `docs/` on how to set up the ``--log-service slack`` feature via Slack
2. Logic is not robust - e.g. when `msg["done"] == msg["total"]`, this does not mean the workflow is complete (checkpoints)
3. The implementation of  ``--log-service slack`` is synchronous, meaning that Snakemake …
> fix: Slack log service

- docs/getting_started/migration.rst
- snakemake/dag.py
> fix: ensure that log and benchmark files are uploaded to storage as well

- snakemake/workflow.py
- tests/test_pep_pathlib/Snakefile
- tests/test_pep_pathlib/pep/config.yaml
- tests/test_pep_pathlib/pep/sample_table.csv
- tests/test_pep_pathlib/workflow/schemas/pep.yaml
- tests/tests.py
This PR allows `pepfile` and `pepschema` to take a `pathlib.Path` object.
> fix: allow pepfile and pepschema to take pathlib

- docs/tutorial/short.rst
Notebook has to end on .py.ipynb or .r.ipynb but in step 6 of the short docs it says:
"
Instead of a shell command, we use Snakemake's Jupyter notebook integration by specifying
notebook:
"notebooks/plot-quals.py"
"
causing the following error:
"
RuleException:
WorkflowError in file _path-to-project_/workflow/Snakefile, line 43:
Notebook to edit has to end on .py.ipynb or .r.ipynb in order to decide which programming language shall be used.
File "_path-to-project_/workflow/Snakefile", line 43, in __rule_plot_quals
File "/home/_username_/miniconda3/envs/snakemake/lib/python3.11/concurrent/futures/thread.py", line 58, in run
"
A simple fix was to use a name ending with .py.ipynb
> fix: fix command in short.rst

- docs/snakefiles/deployment.rst
- docs/snakefiles/modularization.rst
- docs/snakefiles/rules.rst
- docs/tutorial/additional_features.rst
- docs/tutorial/short.rst
- snakemake/cli.py
The new `--software-deployment-method`/`--deployment-method`/`--deployment` is probably a heavily used option for most users, so I think it would benefit from a shorthand option as it is quite verbose. Seems `-m` is available and is kind of related.
I've also updated the docs with some references to this shorthand version and replaced some longform usage with the short option, ensuring it is made clear what the shorthand option is an alias for. Happy to change this though.
> feat: add --sdm short opt for --deployment

- snakemake/parser.py
- tests/test_fstring/Snakefile
fix #2586 for some cases do not considered in #2485
> fix: single line f-string format error in py3.12

- tests/test_issue1256/Snakefile
- tests/tests.py
Add test for issues #1256 and #2574.
The test Snakefile has a syntax error on line 9. Some versions of Snakemake, including 8.0.1, incorrectly report the error on line 20. I'm only submitting the test case, not the fix.
> test: Add test for issue #1256 and #2574

- snakemake/dag.py
- snakemake/io.py
> fix: local mtime handling in case of storage plugins and cleaner error message for parallel storage retrieval

- setup.cfg
- snakemake/cli.py
- snakemake/scheduler.py
- test-environment.yml
The latest update of pulp 2.8.0 removed deprecated API calls still used by snakemake.
This PR updates the calls to their modern equivalents, as well as constrains the pulp version to the moment these got introduced (v2.3.1).
Fixes the issues described in #2607 and #2606.
> fix: Migrate away from deprecated pulp API

- snakemake/cli.py
The second check in cli.py needs to be also looking at args.preemptible_rules, and not the (not defined yet) variable that is intended to be set.
> fix: bug with preemptible rules

- snakemake/api.py
- snakemake/workflow.py
This avoids the error `AttributeError: 'NoneType' object has no attribute 'local_groupid'`, e.g. occurring when trying to create a report
> fix: use default group settings if not execution workflow (fixes attribute error occurring with --report)

- snakemake/logging.py
Fixes #2390 by not providing a Snakefile as it is anyway not used in the web server.
> fix: do not pass snakefile as metadata when wms monitor flag is used

- snakemake/rules.py
> fix: fix false complaints about rules with multiple output files

- snakemake/api.py
> fix: do not require cores to be set for rule-level methods of the workflow API or the corresponding CLI commands (e.g. --lint).

- docs/getting_started/migration.rst
Migration guide: fixes a typo and a wrong link (the original link was self-referential).
> fix: migration guide typo and wrong link

- snakemake/linting/rules.py
> docs: fix typo in `rules.py`

- snakemake/cli.py
- snakemake/settings.py
- tests/test_args.py
Fixes #2643. Seems to have been a refactor gone awry. Argparse "type" fuctions (*a la* `add_argument(type=XXXX)`) take str and produce some type. `parse_batch()` seems to expect an argparse namespace.
This wasn't caught in the unit tests, as they invoke `snakemake.run()` directly in a way that bypasses the CLI arg parsing, which is where this bug is. ~~Not sure what to do about that.~~ (wrote some tests)
> fix: batch bug #2643

- snakemake/workflow.py
- tests/common.py
- tests/tests.py
Potential fix for #2637. 
Edit:
Also adds test case for `conda-create-envs-only`.
> fix: set ignore_incomplete to False in create_conda_envs 

- snakemake/parser.py
- tests/test_fstring/Snakefile
fix: #2648
now, the f-string will never be parsed by `self.state(token)`
> fix: f-string in a more robust style?

- snakemake/workflow.py
`--rulegraph` displays no output , the fix is to add print statement to `self.dag.rule_dot()`
> fix: output of rulegraph, closes #2656

- snakemake/ioutils.py
A regex with a non-raw pattern string was introduced in ca7a6022bacae77be45068adbf4386c2c93fb481 that generates a `SyntaxWarning` about an invalid escape sequence `\{`.
This actually causes me to see test failures while trying to update the [`snakemake` package in Fedora Linux](https://src.fedoraproject.org/rpms/snakemake), e.g.:
```
______________________ test_lint[absolute_paths-positive] ______________________
lint = PosixPath('/builddir/build/BUILD/snakemake-8.4.3/tests/linting/absolute_paths')
case = 'positive'
@pytest.mark.parametrize(
"lint, case", product(os.listdir(LINT_DIR), ["positive", "negative"])
)
def test_lint(lint, case):
lint = LINT_DIR.joinpath(lint)
try:
out = (
sp.check_output(
[   
"/usr/bin/python3",
"-m",
"snakemake",
"--lint",
"--directory",
str(lint), …
```
> fix: SyntaxWarning due to invalid escape sequences in non-raw regex pattern string

- snakemake/api.py
> fix: for local execution, always unrestrictedly assume shared FS

- README.md
As scientific projects move more and more away from X and into the Fediverse, I seemed it appropriate to add your fediverse follow badge @johanneskoester ;-)
Created with https://shields.io/badges/mastodon-follow - alas, users have to click on the right number. Solution unknown.
> docs: added Mastodon follow label with just 'Follow' similar to X

- snakemake/cli.py
- snakemake/resources.py
- snakemake/settings.py
- snakemake/spawn_jobs.py
- snakemake/workflow.py
- tests/tests.py
> fix: various bug fixes for resource parsing

- docs/tutorial/advanced.rst
The usage of the CLI parameter --cores changed. I adapted the description in tutorial to that change.
> docs: fix explanation on how to use all cores in tutorial

- snakemake/cli.py
- tests/tests.py
> feat: allow default storage provider to be explicitly set to none

- setup.cfg
Increases the maximum version bound on `smart_open` to `<8.0` to allow the current `7.x` releases.
https://github.com/piskvorky/smart_open/releases/tag/v7.0.1
The release notes don’t seem to call out any significant breaking changes.
It’s difficult for me to run the full set of tests offline, so I’m relying on CI to double-check this.
> feat: Allow smart_open 7.x

- setup.cfg
- snakemake/cli.py
- snakemake/spawn_jobs.py
- test-environment.yml
- tests/test_set_resources_complex/Snakefile
> fix: use base64 encoding when passing resources and threads to remote jobs (this solves issues with complex quoted resources)

- snakemake/cli.py
- snakemake/spawn_jobs.py
> fix: use base64 encoding for passing default resources args to jobs

- docs/snakefiles/deployment.rst
- snakemake/deployment/conda.py
Fixes #2748.
Ensure that conda's default packages are not installed by Snakemake.
> fix: remove default packages from conda envs

- snakemake/rules.py
> fix: only constrain by --max-threads if threads of job are already known

- snakemake/workflow.py
`cleanup_metadata()` in `workflow.py` is passed a list of `pathlib.Path` objects. This leads to an error when it ought to raise a WorkflowError on cleanup failing for some paths. Given how the function is written, the `failed` list should consist of strings, rather than `Path` objects, otherwise we get:
```
TypeError: sequence item 0: expected str instance, PosixPath found
```
This seems the be a regression in 8.x. vis-a-vis 7.x. I haven't added any tests since the function seems not to be covered by tests so far.
> fix: failure message in cleanup_metadata

- docs/requirements.txt
Fixes #2813. `snakemake` and `snakemake-interface-report-plugins` were missing from the req.txt, which are needed to get the argument parser from `snakemake.cli`.
Note: it seems the default report plugin's arguments leak into the docs (see below)
> docs: add snakemake and reportplugins to req.txt to show all cli options

- snakemake/io.py
> fix: retrieve files from storage if necessary when calling their open method (e.g. when accessing output files from a checkpoint)

- setup.cfg
Update the minimum version requirement for "smart-open" to ">=4.0". This will prevent #2765 when using smart-open 3. 
I have also made a PR to the bioconda recipe with a similar change. 
https://github.com/bioconda/bioconda-recipes/pull/47374
> chore: Update min version requirement for smart-open

- .github/workflows/main.yml
- snakemake/scheduler.py
> fix: only download input for local jobs in the main process, not within remote groups

- docs/snakefiles/rules.rst
- snakemake/jobs.py
- snakemake/template_rendering/__init__.py
> fix: check template rendering output for leaked input file paths

- snakemake/api.py
This is just a small typo fix. 
Working on a fix for https://github.com/snakemake/snakemake-executor-plugin-kubernetes/issues/19 and eventually ended up at the following error when deploying to kubernetes:
```
Error: Error when applying default storage provider gcs to upload workflow sources. {query_validity}
```
Fixing this here so the error is more clear since it looks like kubernetes uses the docker container from main.
> fix: small typo in error

- docs/snakefiles/deployment.rst
Fixes a typo that breaks the link and link text for RO Crate in the docs.
> docs: fix typo and link for RO Crate

- snakemake/utils.py
Follow up to #2312, Python 3.12 also [removed](https://docs.python.org/3.12/whatsnew/3.12.html#removed) bundled `setuptools` (aka `pkg_resources`)
> fix: replace pkg_resources for python 3.12

- snakemake/logging.py
- tests/test_issue2826_failed_binary_logs/Snakefile
- tests/tests.py
As described in #2826 currently the whole snakemake execution crashes if a log file is binary and `show-failed-logs` is used.
This fix prevents the crash by capturing the `UnicodeDecodeError` and returning an error message that the log file is not a text instead.
> fix: Prevent binary log files to crash snakemake execution with `show-failed-logs`

- .github/workflows/codespell.yml
- docs/snakefiles/deployment.rst
- snakemake/dag.py
> fix: omit norun jobs when determining remote storage input file retrieval

- docs/snakefiles/rules.rst
- snakemake/path_modifier.py
- snakemake/spawn_jobs.py
> fix: bug when requesting extended benchmark with slurm

- snakemake/sourcecache.py
> fix: ignore errors when cleaning up runtime cache

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- snakemake/cli.py
> fix: properly restrict scheduler if --jobs/-j is used (in contrast to --cores) in local execution

- snakemake/cli.py
- snakemake/spawn_jobs.py
- tests/common.py
- tests/test_singularity/qsub
- tests/tests.py
Fixes https://github.com/snakemake/snakemake/issues/2808 and https://github.com/snakemake/snakemake/issues/2872 by using base64 encoding when passing apptainer args to spawned jobs.
> fix: fix quoting issues when passing complex apptainer args to spawned jobs

- docs/snakefiles/rules.rst
- snakemake/ioutils.py
- tests/test_ioutils/Snakefile
> feat: support for default value specification when using lookup helper function

- docs/project_info/faq.rst
Update the FAQ entry 'How do I make my rule fail if an output file is empty?' to point the user to the `ensure(... , non_empty=True)` function documentation.
Please check that the :ref: link (intended to point to https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#ensuring-output-file-properties-like-non-emptyness-or-checksum-compliance) is correct - I'm not familiar enough with sphinx to be 100% confident.
> docs: update FAQ - recommend ensure function for failing on empty output

- snakemake/parser.py
- tests/test_fstring/Snakefile
This is another (and hopefully the last) fix for f-string change in python3.12.
Now everthing inner f-string are ignored, and only care about where f-string start and end, and read it from snakefile as-is.
will fix #2881 and fix #2657
related PR: #2864, #2649
> fix: parse f-string as-is from source

- snakemake/rules.py
Updated three errors in rule parsing to throw `RuleException` instead of `SyntaxError` - that way the user feedback includes line numbers to help them identify the source of the error. Fixes issue #2924
> fix: include more context to syntax errors when rule parsing fails (#2924)

- snakemake/dag.py
> fix: sanitize old local storage copies before evaluating params or resource functions

- snakemake/cli.py
I'm rebuilding RPM packages to check build reproducibility (https://docs.fedoraproject.org/en-US/reproducible-builds/), and we got the result that rebuilds of the snakemake man page varies in this trivial way:
```
│ │ │ -<dataclasses._MISSING_TYPE object at 0x3ff87071a90>)
│ │ │ +<dataclasses._MISSING_TYPE object at 0xffff819c5a90>)
```
I think that printing those values is not useful at all (apart from created a problem for reproducible builds efforts), because those values are not interesting at all for the user. So change the argument parser definition to suppress all "boring" values like "set()", "None", "<dataclasses._MISSING_TYPE object at 0x…".
Also, suppress the printing of the default for local cores. It depends on the local machine configuration, but it also makes the user think …
> fix: suppress printing of non-constant or uninteresting defaults in --help

- snakemake/cli.py
- snakemake/spawn_jobs.py
> fix: ensure that envvars in local storage prefix are not prematurely expanded by the shell

- .github/workflows/main.yml
- .github/workflows/release-please.yml
some of the CI actions still refer to actions/checkout@v3, which uses the deprecated node.js v16 and which will soon stop working.
> chore: upgrade actions/checkout to v4

- docs/getting_started/migration.rst
There are entries for the deprecated cluster commands but it's a bit unclear at first that a plugin has to be installed. Tried to make it more clear.
> docs: Make it more clear that the cluster commands now require a plugin

- docs/getting_started/installation.rst
We should recommend people to use Miniforge, since it is now merged with Mambaforge and from the README of the link
> Given its wide usage, there are no plans to deprecate Mambaforge. If at some point we decide to deprecate Mambaforge, it will be appropriately announced and communicated with sufficient time in advance.
>
> That said, if you had to start using one today, we recommend to stick to Miniforge.
In any case the link doesn't quite work since the `#mambaforge` part doesn't actually bring you to the relevant part of the README
> docs: Update installation.rst to recommend Miniforge instead of Mambaforge

- snakemake/storage.py
> fix: use query from storage object in order to be able to reflect possible modifications (via StorageProvider.postprocess_query())

- pyproject.toml
Widen the version bounds on the `pulp` dependency to allow releases in the 3.0.x series. Continue to respect the existing practice of pinning to the minor release. Therefore, `"pulp>=2.3.1,<2.10"` becomes `"pulp>=2.3.1,<3.1"`.
Looking at the changes in https://github.com/coin-or/pulp/compare/2.9.0...3.0.0, there were some minor changes in model-specific APIs. For example, the `strong` keyword to the `COIN_CMD` initializer was changed from a `bool` to an `int`. However, I did not see anything that looked like it would affect the generic APIs used in Snakemake, and the tests that I was able to run locally (not all of them, to be sure) did not show any obvious pulp-related regressions.
The current release of PuLP is [3.0.2](https://pypi.org/project/PuLP/3.0.2/).
> chore: Allow PuLP 3.0

- pyproject.toml
Similar to https://github.com/snakemake/snakemake/pull/3609 and previous PR’s. Now the current version of PuLP is [3.3.0](https://github.com/coin-or/pulp/releases/tag/3.3.0). Nothing in the changes [from 3.2.2 to 3.3.0](https://github.com/coin-or/pulp/compare/3.2.2...3.3.0) seems like it should cause any obvious problems for Snakemake, so let’s try to keep up with the latest PuLP releases.
> chore: Allow PuLP 3.3
