snakemake/remote/AzureStorage.py
snakemake/remote/S3.py

Fix keyword args for azure storage and S3.

---

snakemake/io.py
snakemake/jobs.py

fix follow symlinks on all platforms.

---

snakemake/logging.py
snakemake/workflow.py

Fix logger cleanup.

---

docs/getting_started/examples.rst

tex.smrules - > tex.rules

---

misc/vim/syntax/snakemake.vim

This PR adds the `wildcard_constraints` directive to the snakemake.vim syntax file so that it gets highlighted in vim.

Update snakemake vim

---

docs/tutorial/short.rst

Updated name of the downloaded test data: 
v5.2.3.tar.bz2 -> v5.4.5.tar.gz

Update short tutorial code snippet: unpacking data

---

docs/index.rst

Old link is expiring, replace with the new link it suggests.

Update Singularity Link in docs index file

---

snakemake/__init__.py
snakemake/logging.py

Add a log handler script argument for custom log handling

add option for log handler script

---

snakemake/executors.py
snakemake/scheduler.py

fix for https://github.com/snakemake/snakemake/issues/166

add container-image parameter for tibanna

---

.sonarcloud.properties
examples/hello-world/Snakefile
examples/hello-world/config.yaml
examples/hello-world/envs/matplotlib.yaml
examples/hello-world/envs/xsv.yaml
examples/hello-world/scripts/plot-hist.py
snakemake/io.py
snakemake/jobs.py
snakemake/notebook.py
snakemake/script.py

This PR adds an easy to understand example that should be accessible to anybody, regardless of the scientific field, while showing all important features of Snakemake.

Add universal hello world example

---

.github/workflows/main.yml

Such that the test suite also works on forks.

split tests and make AWS tests optional

---

snakemake/workflow.py
tests/test_subworkflow_config/Snakefile
tests/test_subworkflow_config/environment.yml
tests/test_subworkflow_config/sub.snake

Continuation of PR #42, in order to fix formatting.

Fix subworkflowconfig

---

docs/executing/caching.rst
snakemake/__init__.py
snakemake/caching/local.py
snakemake/caching/remote.py
snakemake/executors.py
snakemake/parser.py
snakemake/workflow.py
tests/test_output_file_cache/Snakefile
tests/tests.py

Allowing to write this:
```
rule download_data:
output:
"results/data/worldcitiespop.csv"
cache: True
shell:
"curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output}"
```

Cache directive

---

snakemake/linting/__init__.py

Lint all rules and included snakefiles
Fixes #310

Lint all items

---

snakemake/__init__.py
snakemake/deployment/conda.py
snakemake/workflow.py

Optionally enable a more extensive conda cleanup, that also removes unused package caches.

---

snakemake/parser.py

For issue #335:
Added " and checkpoint" to parser error to help debugging.

expanded on error message to allow for checkpoint

---

snakemake/__init__.py
snakemake/rules.py
snakemake/scheduler.py
snakemake/workflow.py

This does not change behavior, but yields more consistent experience.

Set cores resource to None if not executing locally.

---

snakemake/caching/local.py

Fix caching of directories

---

snakemake/workflow.py

account for XRootD paths not appearing absolute

---

.github/workflows/main.yml
docs/executing/cluster-cloud.rst
snakemake/__init__.py
snakemake/common.py
snakemake/executors.py
snakemake/scheduler.py
snakemake/workflow.py
test-environment.yml
tests/common.py
tests/test_benchmark/script.py
tests/test_get_log_both/wrapper.py
tests/test_get_log_complex/wrapper.py
tests/test_get_log_none/wrapper.py
tests/test_get_log_stderr/wrapper.py
tests/test_get_log_stdout/wrapper.py
tests/test_google_lifesciences.py
tests/test_google_lifesciences/Snakefile
tests/test_google_lifesciences/config.json
tests/test_google_lifesciences/env.yml
tests/test_issue1046/my_wrapper/wrapper.py
tests/test_issue916/pythonTest.py
tests/test_static_remote/S3MockedForStaticTest.py
tests/test_tibanna/cleanup.py
tests/test_tibanna/scripts/step2.py
tests/tests.py

[WIP] Adding Google Life Science support

---

snakemake/io.py
snakemake/notebook.py
snakemake/remote/__init__.py
snakemake/resources.py
snakemake/script.py

This will fix regular expression warnings that appear in testing. See #386 for the warnings, and the fixes represented here. This will close #386.

adding r for raw strings to fix regular expression warnings

---

snakemake/script.py

This should partially fix issue #277. The other part would be to minimize requests to the wrapper repository.

git_content returns string, encode into bytes instead.

---

docs/executor_tutorial/google_lifesciences.rst
snakemake/executors/google_lifesciences.py

There is a bug that the snakemake-testing bucket is hard coded into the executor - I don't know how we both missed this @johanneskoester ! This is a quick fix for that.

fixing bug with hardcoded snakemake-testing

---

snakemake/script.py

Changed the detection of the python version installed in the current environment to `sys.version_info` instead of `--version`.

Changed py_version detection

---

docs/index.rst

Another publication using snakemake.

Update list of publications using snakemake in docs/index.rst

---

snakemake/executors/__init__.py
test-environment.yml
tests/test_tes/Snakefile

* Replace manual requests to TES instance with [`py-tes`](https://github.com/ohsu-comp-bio/py-tes) client
* Add dependency `py-tes` to `test-environment.yml` (requires installation via `pip` as it is unavailable via `conda`)
* Add support for the following TES task resources:
* `cpu_cores`: use Snakemake's `resources["_cores"]`
* `ram_gb`: use Snakemake's `resources["mem_mb"]` divided by 1000
* `disk_gb`: use Snakemake's `resources["disk_mb"]` divided by 1000
* Add resource requirements to some jobs in `tests/test_tes`

Use py-tes client and add support for task resources

---

docs/project_info/authors.rst

This is a teeny tiny PR to add my name to the list of contributors! I was browsing the docs and didn't realize that it was there.

adding vsoch to list of contributors

---

docs/executor_tutorial/google_lifesciences.rst

Add mamba instructions to google_lifesciences.rst

---

docs/executor_tutorial/google_lifesciences.rst

This is one more update to the Google lifesciences tutorial documentation to fix a few blocks of incorrect spacing, and consistently use environment.yaml instead of environment.yml. It is paired with https://github.com/snakemake/snakemake-tutorial-data/pull/2 so the user downloads a file with the same name and content.

docs: More fixes to google lifesciences tutorial for spacing and links

---

snakemake/executors/google_lifesciences.py

fixing bug with crc32c import

---

docs/executor_tutorial/google_lifesciences.rst
snakemake/executors/google_lifesciences.py

This PR includes updates (suggestions from @hnawar) to increase the default disk size, and add more scoped credentials. @hnawar, please feel free to comment on the PR / make suggestions! If there are other changes you'd like to see and the PR isn't merged yet, please add them here and I'll update it.

Updating gls docs with suggestions from Hatem

---

snakemake/scheduler.py

This PR includes all jobs which have not been executed including jobs not being ready yet for improvement calculation.

Fix target function of ilp scheduler

---

snakemake/report/__init__.py

Support pathlib.Path for configfile when generating report

---

misc/vim/README.md
misc/vim/ftdetect/snakemake.vim
misc/vim/syntax/snakemake.vim

Updated vim files
- Utilize syntax guard for current_syntax
- Use ftdetect instead of au commands in vimrc
- Update readme, placing plugin managers before manual installation

Update vim plugin

---

snakemake/io.py
snakemake/remote/GS.py
snakemake/remote/__init__.py

Reverts snakemake/snakemake#675

Revert "Threaded local iocache"

---

docs/executing/cloud.rst
docs/project_info/contributing.rst

Update source activate to conda activate in docs

---

snakemake/report/__init__.py
tests/test_report/Snakefile

Thanks to @jbloom for pointing me to the issue.

fix issue #682.

---

snakemake/dag.py
snakemake/io.py
snakemake/jobs.py
snakemake/output_index.py
snakemake/workflow.py

Some of the optimizations in PR #697 have become superfluous due to previous optimizations from PR #710. The rest has been included here, in slightly different ways but the ideas are the same.
In the squash merge, mention @jmeppley!

Further speed improvements inspired by PR #697

---

snakemake/common.py
snakemake/io.py

Reverts snakemake/snakemake#731 in favor of snakemake/snakemake#726

Revert "add and use compat shims for python3.6"

---

snakemake/__init__.py
snakemake/workflow.py

add option not to evaluate or execute subworkflows

---

docs/snakefiles/modularization.rst
docs/snakefiles/rules.rst
snakemake/caching/hash.py
snakemake/cwl.py
snakemake/notebook.py
snakemake/report/__init__.py
snakemake/script.py
tests/test_jupyter_notebook/Snakefile

Allow wildcards in notebook, script, wrapper, and cwl directives.

---

docs/tutorial/setup.rst

Hi @johanneskoester, 
Following up on our chat on Friday I tested setting up the tutorial environment on the WSL and it seems to work fine. I've updated the relevant section of the tutorial in this PR.

Added WSL to the tutorial

---

snakemake/report/__init__.py

Slightly modified version of #803, also fixing the issue reported by @boulund.

fix report datetime retrieval

---

docs/snakefiles/deployment.rst
snakemake/__init__.py
snakemake/executors/__init__.py
snakemake/executors/google_lifesciences.py
snakemake/shell.py
snakemake/workflow.py

(can be deactivated via the command line).

remove R_LIBS, PYTHONPATH, etc. when using conda env

---

docs/project_info/contributing.rst

There is no file named `environment.yml`.

contributing.rst: Fixed conda environment file names

---

docs/project_info/citations.rst

Make version number consistent with badge example

Badge example: version number

---

docs/executing/cluster.rst

Hello! Just noticed this as I was reading through the docs and wanted to point it out. Have a great day!

Fix very small sentence error in docs

---

CHANGELOG.rst
snakemake/executors/__init__.py
snakemake/executors/google_lifesciences_helper.py
tests/common.py

Refactored some f-strings to restore python 3.5 compatibility.

Refactor f-strings

---

docs/getting_started/installation.rst
docs/snakefiles/deployment.rst
docs/tutorial/additional_features.rst
docs/tutorial/setup.rst
snakemake/__init__.py
snakemake/deployment/conda.py

Also adds an informative error message if mamba cannot be found.

Change default conda frontend to mamba

---

snakemake/checkpoints.py
snakemake/io.py

Tried to also make this a little more readable / more easily adjusted without getting into formatting issues.

Fix temp() breaks checkpoints (fixes #966)

---

docs/tutorial/advanced.rst

Add missing def for `get_bwa_map_input_fastqs`

---

snakemake/ruleinfo.py
snakemake/workflow.py
tests/test_singularity_module/Snakefile
tests/test_singularity_module/module.smk
tests/test_singularity_module/script.py
tests/tests.py

Fixes issue snakemake/snakedeploy#16.

Fix container images in modules not being considered so far.

---

snakemake/executors/__init__.py
snakemake/executors/google_lifesciences.py
snakemake/remote/GS.py
snakemake/resources.py

This adds retries to google API calls in the life sciences backend.

Fix google API timeouts in life science backend

---

snakemake/rules.py
tests/tests.py

Fix frac resources

---

docs/index.rst

Fix wrongly placed comma in index.rst

Fix wrongly placed comma in index.rst

---

README.md

Don't want anyone to feel like this isn't maintained anymore when it's in fact super active ;)

Update Readme.md: Copyright to include 2021

---

snakemake/exceptions.py
snakemake/rules.py
snakemake/scheduler.py

Bug fixes and usability improvements for checkpoint handling

---

snakemake/resources.py
tests/common.py
tests/test_github_issue1069/Snakefile
tests/tests.py

And added testcase. In addition, added machinery to test the CLI without boilerplate (use shellcmd= in the run() function in tests.py).

fix: issue #1069

---

docs/snakefiles/configuration.rst

Adds links to eido and how to write a PEP schema guide

Add `pepschema` directive in the documentation

---

.github/workflows/main.yml
snakemake/utils.py

Try to fix a recent issue with actions: https://github.com/snakemake/snakemake/pull/1111/checks?check_run_id=3183313089

chore: use checkout v2

---

snakemake/linting/snakefiles.py

fix: linting of remote snakefiles

---

snakemake/__init__.py

It can be installed with `conda install -n base -c conda-forge mamba`. "

Fix type in __init__.py -> `. "

---

tests/common.py

Fixes a bug presumably introduced with #1283.

fix: set default number of nodes to 1 in test cases

---

snakemake/__init__.py
snakemake/_version.py
snakemake/benchmark.py
snakemake/cwl.py
snakemake/exceptions.py
snakemake/executors/__init__.py
snakemake/io.py
snakemake/remote/GS.py
snakemake/remote/S3Mocked.py
snakemake/remote/__init__.py
snakemake/script.py
snakemake/unit_tests/__init__.py
snakemake/utils.py
tests/common.py
tests/test_google_lifesciences.py
tests/test_static_remote/S3MockedForStaticTest.py
tests/testapi.py
tests/tests.py
versioneer.py

Fixed misspellings, typos, and duplicated words in docstrings
Added articles and commas to docstrings.

fix: fixed misspellings and typos in docstrings

---

snakemake/logging.py

fix: atomic job error display

---

.gitpod.yml
snakemake/executors/__init__.py
snakemake/executors/ga4gh_tes.py
snakemake/executors/google_lifesciences.py
tests/common.py

chore: dbg docker image usage in CI

---

.github/workflows/main.yml

chore: temporarily disable gcloud testing because we have entirely used up the free budget

---

snakemake/report/template/components/content.js
snakemake/report/template/components/rule_graph.js
tests/test_google_lifesciences.py
tests/test_kubernetes.py

fix: modify dag and workflow display in report to also work for big DAGs

---

docs/project_info/faq.rst

A few minor suggestions for readability. I realize this can be subjective so feel free to disregard as needed.

docs: Small modifications to the FAQ

---

.github/workflows/main.yml

chore: constrain singularity to work around missing zlib

---

snakemake/dag.py
snakemake/io.py

fix: better error messages in case of missing files after latency period

---

snakemake/parser.py
tests/test_modules_all/module-test/Snakefile

fix: fixed detection of norun rules inside of modules

---

snakemake/io.py
snakemake/jobs.py
snakemake/sourcecache.py
snakemake/workflow.py

refactor: cleaner caching persistence detection in sourcecache module

---

.github/workflows/main.yml

chore: fix mamba deployment in CI

---

tests/test_profile/config.yaml

chore: extend profile testcase to include --set-threads handling

---

snakemake/dag.py
snakemake/io.py
snakemake/persistence.py

feat: for small files, compare checksums to determine if job needs to run if input file is newer than output file

---

.github/workflows/main.yml

Test for deploying slurm via an ansible playbook.

chore: setup slurm via ansible

---

snakemake/workflow.py

fix: improved provenance trigger info

---

snakemake/executors/google_lifesciences.py

fix: fix regression in workflow source acquisition of google life science executor

---

snakemake/dag.py
snakemake/jobs.py
snakemake/workflow.py

feat: print reason summary in case of dryrun

---

snakemake/exceptions.py
snakemake/jobs.py
snakemake/rules.py

This should help with debugging workflows.

fix: more comprehensive error reporting for RuleExceptions

---

docs/project_info/faq.rst

A very trivial doc fix, --forcerules is really --forcerun

docs: Update faq.rst / forcerun flag

---

tests/test_kubernetes.py

Fixes a bug in tests introduced in #1858

fix: allocation of local ssds in k8s tests

---

docs/tutorial/tutorial.rst

docs: fix grammar in the intro

---

docs/snakefiles/deployment.rst

Replace `metatada` with `metadata` in the docs

docs: fix typo

---

snakemake/common/tbdstring.py

fix: issue 1846

---

snakemake/exceptions.py

fix: fix typo in line display of exceptions

---

snakemake/caching/hash.py
snakemake/report/__init__.py

fix: regression ValueError introduced with 7.17.2

---

.github/workflows/main.yml

dbg slurm executor PR

---

.github/workflows/main.yml
tests/test_slurm_mpi/Snakefile

chore: simplify slurm config

---

snakemake/dag.py

feat: provide information about temp, pipe, and service files in --summary

---

snakemake/__init__.py
snakemake/logging.py
snakemake/workflow.py

fix: avoid logfile writing in case of dryrun; better hints in case of incomplete checkpoints

---

snakemake/remote/zenodo.py

fix: handle case where zenodo deposition does not return files

---

docs/executing/cloud.rst
docs/executing/cluster.rst
docs/snakefiles/rules.rst
snakemake/executors/slurm/slurm_jobstep.py
snakemake/executors/slurm/slurm_submit.py
snakemake/resources.py
snakemake/rules.py

fix: improved default resources parsing (also allowing to deactivate a default resource via setting it to None)

---

.github/workflows/main.yml
snakemake/executors/__init__.py
snakemake/script.py

fix: make python version check more robust

---

docs/executing/cli.rst

docs: mention XDG_CACHE_HOME

---

docs/snakefiles/reporting.rst
snakemake/exceptions.py
snakemake/persistence.py
snakemake/report/__init__.py

feat:  allow input, output, and params to be used in functions passed to report mark arguments

---

snakemake/utils.py

fix: properly handle NA values for paramspaces

---

snakemake/__init__.py
snakemake/persistence.py
snakemake/workflow.py
tests/test_persistence.py

Closes #2078. I've created an isolated test case, and have also tested it in the wild. Couldn't figure out how to make a test for a proper pipeline run though. Hope the test case I've added is sufficient though.

feat: add cleanup containers option

---

.github/workflows/main.yml

chore: fix CI deployment on windows

---

snakemake/executors/slurm/slurm_submit.py

When using --slurm, exiting snakemake by SIGINT or ctrl-c helpfully cancels spawned jobs. However, this is quite unreliable as it often hangs for a few minutes and exits without canceling the jobs in the end (without indicating that it failed either).
Slurm documentation on [scancel](https://slurm.schedmd.com/scancel.html#SECTION_PERFORMANCE) notes that a large number of scancel calls at the same time may result in denial of service.
Snakemake runs scancel on each job [individually](https://github.com/snakemake/snakemake/blob/main/snakemake/executors/slurm/slurm_submit.py#L136). Instead, job ids should be collected and cancelled all at once.
fixes #2113

fix: batch collect jobs for scancel

---

snakemake/exceptions.py

Cosmetics for exception/error message printing.

refactor: add missing linebreak in error handling

---

snakemake/dag.py
snakemake/report/template/components/rule_graph.js

Fix batch issue #2055
This is a PR related to issue #2055.

fix: rounding for batch calculation

---

snakemake/io.py

fix: raise error if callable is passed to expand.

---

tests/test_conda_function/Snakefile
tests/test_conda_named/Snakefile

chore: fix CI failures

---

misc/nano/syntax/snakemake.nanorc
misc/vim/syntax/snakemake.vim

Include syntax highlighting for the recently added `localrule` directive.
* [NA] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [NA] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

chore: add localrule directive to syntax highlighting

---

.github/workflows/main.yml

chore: fix slurm setup in CI

---

snakemake/deployment/singularity.py

fix: quote paths given to singularity in order to ensure that it does not fail when paths contain whitespace

---

misc/vim/README.md

`packer.nvim` is a popular lua-based packet manager for nvim, this info might help a lot of people.
The added line can go into the lua config file for nvim.

docs: update misc/vim/Readme with info for packer.nvim

---

snakemake/modules.py

fix: fix missed wildcard constraints when using local rule inheritance

---

docs/executing/cli.rst
snakemake/profiles.py
snakemake/workflow.py

feat: allow profiles to be YTE templates; adapt to eido 2.0

---

.github/workflows/main.yml
.github/workflows/test-flux.yaml
setup.cfg
snakemake/__init__.py
snakemake/dag.py
snakemake/executors/__init__.py
snakemake/executors/azure_batch.py
snakemake/executors/flux.py
snakemake/executors/ga4gh_tes.py
snakemake/executors/google_lifesciences.py
snakemake/executors/slurm/slurm_jobstep.py
snakemake/executors/slurm/slurm_submit.py
snakemake/interfaces.py
snakemake/jobs.py
snakemake/persistence.py
snakemake/scheduler.py
snakemake/workflow.py
test-environment.yml
tests/test_singularity/Snakefile

refactor: define consistent abstract base classes for jobs

---

.github/workflows/main.yml

chore: use latest release of ansible roles for slurm setup

---

CHANGELOG.md

Resolves #2369 
Add changelog entry for Python version bump
See https://github.com/snakemake/snakemake/pull/2341#issuecomment-1648487223

docs: update CHANGELOG.md: add minimum Python version bump

---

snakemake/common/__init__.py
snakemake/modules.py

fix: proper reuse of rule proxies when importing several times from the same module

---

snakemake/executors/azure_batch.py

fix: import

---

snakemake/report/__init__.py
snakemake/report/template/components/abstract_menu.js
snakemake/report/template/components/abstract_results.js
snakemake/report/template/components/category.js
snakemake/report/template/components/common.js
snakemake/report/template/components/menu.js
tests/common.py

fix: sort report (sub-)categories in lexicographical order

---

snakemake/executors/dryrun.py
snakemake/executors/flux.py
snakemake/executors/local.py
snakemake/executors/touch.py
snakemake/jobs.py
snakemake/persistence.py

refactor: cleanup executor interfaces

---

snakemake/cli.py
snakemake/dag.py
snakemake/executors/dryrun.py
snakemake/executors/local.py
snakemake/executors/touch.py
snakemake/io.py
snakemake/jobs.py
snakemake/settings.py
snakemake/spawn_jobs.py
snakemake/storage.py
snakemake/workflow.py
tests/common.py
tests/tests.py

feat: implement precommand

---

snakemake/api.py
snakemake/cli.py
snakemake/settings.py
snakemake/workflow.py

refactor: move exec mode handling into WorkflowSettings

---

snakemake/io.py
snakemake/path_modifier.py
snakemake/rules.py
tests/tests.py

Fixes: https://github.com/snakemake/snakemake/issues/2473

fix: fix storage handling on windows by converting all paths to posix paths

---

snakemake/api.py
snakemake/cli.py
snakemake/dag.py
snakemake/io.py
snakemake/jobs.py
snakemake/settings.py
snakemake/spawn_jobs.py
snakemake/workflow.py
tests/test_script/scripts/test.py

feat: add option to control software deployment mode (shared or non shared FS)

---

.github/workflows/main.yml
test-environment.yml

remove and add as regular dependency as in TODO

chore: add plugins for ci testing to test environment

---

docs/getting_started/migration.rst

Detailed diff between <7 and 8, may be useful for issues such as #2552 and others.

docs: diff 7 and 8

---

snakemake/exceptions.py
snakemake/workflow.py

fix: #2583, #1256 and #2574
maybe #2583

fix: correctly report lineno

---

snakemake/dag.py

fix: deduplicate input files before retrieval from storage

---

docs/executing/grouping.rst
snakemake/dag.py
snakemake/io.py
snakemake/rules.py
snakemake/workflow.py

fix: properly resolve wildcards in group components

---

snakemake/api.py

fix: do not require cores to be set for non-executing modes

---

snakemake/cli.py

fix: use default container image if nothing is provided

---

snakemake/report/data/timeline.py

Fixing X-axis label on report plot

fix: Fixed plot axis label on report

---

snakemake/resources.py

fix: binary mem

---

setup.cfg
snakemake/dag.py
snakemake/executors/touch.py
snakemake/scheduler.py
snakemake/workflow.py

fix: properly handle --touch when using a storage provider

---

setup.cfg
snakemake/io.py

refactor: use lutime and lchmod from snakemake-interface-common

---

setup.cfg

fix: constrain dependencies to match conda experience

---

docs/snakefiles/rules.rst
snakemake/rules.py
tests/test_inner_call/Snakefile
tests/tests.py

Snakemake fails building the DAG when a function containing a inner-function is called within an expand-command.

feat: add ability to return input functions from input functions. Such nesting is evaluated 10 times at most. Beyond that, an error is thrown. 

---

snakemake/jobs.py

fix: fix wait for files in case of using remote storage and remote execution

---

snakemake/report/common.py

fix: error when detecting mime type during report creation

---

docs/snakefiles/rules.rst
setup.cfg
snakemake/api.py
snakemake/cli.py
snakemake/io.py
snakemake/ioutils.py
snakemake/jobs.py
snakemake/scheduler.py
snakemake/settings.py
snakemake/spawn_jobs.py
tests/test_expand_list_of_functions/Snakefile
tests/test_scheduler_sequential_all_cores/Snakefile
tests/test_scheduler_sequential_all_cores/expected-results/test.0.out
tests/test_scheduler_sequential_all_cores/expected-results/test.1.out
tests/tests.py

feat: add setting for defining separate local storage prefix for remote jobs; improved ergonomics for semantic helper functions

---

snakemake/api.py
snakemake/cli.py
snakemake/exceptions.py
snakemake/report/__init__.py
snakemake/settings.py
snakemake/workflow.py
tests/test01/Snakefile

fix: various error handling improvements, fixed logging/error behavior (stdout from dryrun, stderr otherwise)

---

snakemake/dag.py
snakemake/io.py

fix: properly delete local copies of storage files after remote jobs

---

snakemake/cli.py
snakemake/common/__init__.py
snakemake/persistence.py
snakemake/settings.py

fix: respect APPTAINER_CACHEDIR and allow env variables in --apptainer-prefix and --conda-prefix

---

snakemake/dag.py
snakemake/workflow.py

fix: handle async method in cleanup_storage_objects

---

snakemake/io.py
tests/test_modules_all/Snakefile
tests/test_modules_all/module-test/Snakefile
tests/tests.py

fix: expand error on modules with prefix (#1614)

---

snakemake/common/tests/testcases/simple/Snakefile

fix: extend workflow test suite by wildcards with slashes (in order to detect bugs that can occur in executors)

---

snakemake/dag.py

fix: remove non-empty local copies of remote storage dirs

---

snakemake/dag.py

fix: show queries of remote storage files instead of local paths in summary

---

snakemake/io.py

fix: fix missing await when opening checkpoint output

---

snakemake/dag.py
snakemake/io.py
snakemake/scheduler.py
snakemake/workflow.py

fix: make checkpoint updates synchronous

---

docs/executing/cli.rst

fix: typo in workflow specific profile default location

---

snakemake/exceptions.py

fix: fix corner case bug in input function exception handling

---

README.md

docs: add badge for bioconda version

---

docs/snakefiles/rules.rst

docs: fix code block formatting

---

.github/workflows/main.yml
snakemake/common/tests/__init__.py
snakemake/dag.py
snakemake/deployment/conda.py
snakemake/io.py
snakemake/ioutils.py
snakemake/jobs.py
snakemake/notebook.py
snakemake/parser.py
snakemake/persistence.py
snakemake/script/__init__.py
snakemake/sourcecache.py
snakemake/template_rendering/__init__.py
tests/testapi.py

refactor: format with black 0.24

---

setup.cfg
snakemake/api.py
snakemake/dag.py
snakemake/executors/touch.py
snakemake/io.py

fix: implement support for --touch on remote storage (if the storage provider supports it)

---

docs/snakefiles/deployment.rst
docs/snakefiles/rules.rst
docs/tutorial/additional_features.rst
docs/tutorial/advanced.rst
docs/tutorial/basics.rst
docs/tutorial/setup.rst
docs/tutorial/short.rst

docs: use note directive to align with the capabilities of the used theme

---

docs/tutorial/additional_features.rst

docs: fix link markup

---

docs/getting_started/installation.rst

docs: update installation docs to reflect changes in conda ecosystem

---

CHANGELOG.md

Just a typo fix to please codespell.

docs: Fix typo in CHANGELOG.md

---

docs/project_info/codebase.rst

docs: fix link to github.com/snakemake/poetry-snakemake-plugin
